// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: transport/control.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlMessage is the envelope for all C2 traffic on the ControlChannel stream.
type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_Command
	//	*ControlMessage_Event
	//	*ControlMessage_Heartbeat
	//	*ControlMessage_Response
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_transport_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_transport_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_transport_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ControlMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ControlMessage) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ControlMessage_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type ControlMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type ControlMessage_Response struct {
	Response *Response `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

func (*ControlMessage_Command) isControlMessage_Payload() {}

func (*ControlMessage_Event) isControlMessage_Payload() {}

func (*ControlMessage_Heartbeat) isControlMessage_Payload() {}

func (*ControlMessage_Response) isControlMessage_Payload() {}

// Command is sent from controller to steward via ControlChannel.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // sync_config, sync_dna, connect_dataplane, execute_task, shutdown, validate_config
	StewardId     string                 `protobuf:"bytes,3,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_transport_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_transport_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_transport_control_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *Command) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Command) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Command) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Event is sent from steward to controller via ControlChannel.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // config_applied, dna_synced, task_completed, task_failed, error, etc.
	StewardId     string                 `protobuf:"bytes,3,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CommandId     string                 `protobuf:"bytes,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // correlation to originating command
	Details       map[string]string      `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Severity      string                 `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"` // info, warning, error, critical
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_transport_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_transport_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_transport_control_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *Event) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Event) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

// Heartbeat is sent from steward to controller via ControlChannel.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, error, disconnected
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	DnaHash       string                 `protobuf:"bytes,7,opt,name=dna_hash,json=dnaHash,proto3" json:"dna_hash,omitempty"` // for hash-based sync detection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_transport_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_transport_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_transport_control_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *Heartbeat) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Heartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Heartbeat) GetDnaHash() string {
	if x != nil {
		return x.DnaHash
	}
	return ""
}

// Response is sent from steward to controller for command acknowledgment.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	StewardId     string                 `protobuf:"bytes,2,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_transport_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_transport_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_transport_control_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Response) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Response) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_transport_control_proto protoreflect.FileDescriptor

const file_transport_control_proto_rawDesc = "" +
	"\n" +
	"\x17transport/control.proto\x12\x0fcfgms.transport\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x01\n" +
	"\x0eControlMessage\x124\n" +
	"\acommand\x18\x01 \x01(\v2\x18.cfgms.transport.CommandH\x00R\acommand\x12.\n" +
	"\x05event\x18\x02 \x01(\v2\x16.cfgms.transport.EventH\x00R\x05event\x12:\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1a.cfgms.transport.HeartbeatH\x00R\theartbeat\x127\n" +
	"\bresponse\x18\x04 \x01(\v2\x19.cfgms.transport.ResponseH\x00R\bresponseB\t\n" +
	"\apayload\"\xb8\x02\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x03 \x01(\tR\tstewardId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12<\n" +
	"\x06params\x18\x06 \x03(\v2$.cfgms.transport.Command.ParamsEntryR\x06params\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x03 \x01(\tR\tstewardId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"command_id\x18\x06 \x01(\tR\tcommandId\x12=\n" +
	"\adetails\x18\a \x03(\v2#.cfgms.transport.Event.DetailsEntryR\adetails\x12\x1a\n" +
	"\bseverity\x18\b \x01(\tR\bseverity\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12A\n" +
	"\ametrics\x18\x05 \x03(\v2'.cfgms.transport.Heartbeat.MetricsEntryR\ametrics\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x19\n" +
	"\bdna_hash\x18\a \x01(\tR\adnaHash\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x02\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x02 \x01(\tR\tstewardId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\adetails\x18\x06 \x03(\v2&.cfgms.transport.Response.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B,Z*github.com/cfgis/cfgms/api/proto/transportb\x06proto3"

var (
	file_transport_control_proto_rawDescOnce sync.Once
	file_transport_control_proto_rawDescData []byte
)

func file_transport_control_proto_rawDescGZIP() []byte {
	file_transport_control_proto_rawDescOnce.Do(func() {
		file_transport_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_control_proto_rawDesc), len(file_transport_control_proto_rawDesc)))
	})
	return file_transport_control_proto_rawDescData
}

var file_transport_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_transport_control_proto_goTypes = []any{
	(*ControlMessage)(nil),        // 0: cfgms.transport.ControlMessage
	(*Command)(nil),               // 1: cfgms.transport.Command
	(*Event)(nil),                 // 2: cfgms.transport.Event
	(*Heartbeat)(nil),             // 3: cfgms.transport.Heartbeat
	(*Response)(nil),              // 4: cfgms.transport.Response
	nil,                           // 5: cfgms.transport.Command.ParamsEntry
	nil,                           // 6: cfgms.transport.Event.DetailsEntry
	nil,                           // 7: cfgms.transport.Heartbeat.MetricsEntry
	nil,                           // 8: cfgms.transport.Response.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_transport_control_proto_depIdxs = []int32{
	1,  // 0: cfgms.transport.ControlMessage.command:type_name -> cfgms.transport.Command
	2,  // 1: cfgms.transport.ControlMessage.event:type_name -> cfgms.transport.Event
	3,  // 2: cfgms.transport.ControlMessage.heartbeat:type_name -> cfgms.transport.Heartbeat
	4,  // 3: cfgms.transport.ControlMessage.response:type_name -> cfgms.transport.Response
	9,  // 4: cfgms.transport.Command.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 5: cfgms.transport.Command.params:type_name -> cfgms.transport.Command.ParamsEntry
	9,  // 6: cfgms.transport.Event.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 7: cfgms.transport.Event.details:type_name -> cfgms.transport.Event.DetailsEntry
	9,  // 8: cfgms.transport.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 9: cfgms.transport.Heartbeat.metrics:type_name -> cfgms.transport.Heartbeat.MetricsEntry
	9,  // 10: cfgms.transport.Response.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 11: cfgms.transport.Response.details:type_name -> cfgms.transport.Response.DetailsEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_transport_control_proto_init() }
func file_transport_control_proto_init() {
	if File_transport_control_proto != nil {
		return
	}
	file_transport_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_Command)(nil),
		(*ControlMessage_Event)(nil),
		(*ControlMessage_Heartbeat)(nil),
		(*ControlMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_control_proto_rawDesc), len(file_transport_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_control_proto_goTypes,
		DependencyIndexes: file_transport_control_proto_depIdxs,
		MessageInfos:      file_transport_control_proto_msgTypes,
	}.Build()
	File_transport_control_proto = out.File
	file_transport_control_proto_goTypes = nil
	file_transport_control_proto_depIdxs = nil
}
