// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: transport/data.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransferType enumerates the categories of bulk data transferred between components.
type TransferType int32

const (
	TransferType_TRANSFER_TYPE_UNSPECIFIED TransferType = 0
	TransferType_TRANSFER_TYPE_PACKAGE     TransferType = 1
	TransferType_TRANSFER_TYPE_SCRIPT      TransferType = 2
	TransferType_TRANSFER_TYPE_LOG_BATCH   TransferType = 3
	TransferType_TRANSFER_TYPE_BINARY      TransferType = 4
)

// Enum value maps for TransferType.
var (
	TransferType_name = map[int32]string{
		0: "TRANSFER_TYPE_UNSPECIFIED",
		1: "TRANSFER_TYPE_PACKAGE",
		2: "TRANSFER_TYPE_SCRIPT",
		3: "TRANSFER_TYPE_LOG_BATCH",
		4: "TRANSFER_TYPE_BINARY",
	}
	TransferType_value = map[string]int32{
		"TRANSFER_TYPE_UNSPECIFIED": 0,
		"TRANSFER_TYPE_PACKAGE":     1,
		"TRANSFER_TYPE_SCRIPT":      2,
		"TRANSFER_TYPE_LOG_BATCH":   3,
		"TRANSFER_TYPE_BINARY":      4,
	}
)

func (x TransferType) Enum() *TransferType {
	p := new(TransferType)
	*p = x
	return p
}

func (x TransferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferType) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_data_proto_enumTypes[0].Descriptor()
}

func (TransferType) Type() protoreflect.EnumType {
	return &file_transport_data_proto_enumTypes[0]
}

func (x TransferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferType.Descriptor instead.
func (TransferType) EnumDescriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{0}
}

// TaskMessageType enumerates the lifecycle events for task execution streams.
type TaskMessageType int32

const (
	TaskMessageType_TASK_MESSAGE_TYPE_UNSPECIFIED TaskMessageType = 0
	TaskMessageType_TASK_MESSAGE_TYPE_START       TaskMessageType = 1
	TaskMessageType_TASK_MESSAGE_TYPE_PROGRESS    TaskMessageType = 2
	TaskMessageType_TASK_MESSAGE_TYPE_OUTPUT      TaskMessageType = 3
	TaskMessageType_TASK_MESSAGE_TYPE_COMPLETE    TaskMessageType = 4
	TaskMessageType_TASK_MESSAGE_TYPE_CANCEL      TaskMessageType = 5
)

// Enum value maps for TaskMessageType.
var (
	TaskMessageType_name = map[int32]string{
		0: "TASK_MESSAGE_TYPE_UNSPECIFIED",
		1: "TASK_MESSAGE_TYPE_START",
		2: "TASK_MESSAGE_TYPE_PROGRESS",
		3: "TASK_MESSAGE_TYPE_OUTPUT",
		4: "TASK_MESSAGE_TYPE_COMPLETE",
		5: "TASK_MESSAGE_TYPE_CANCEL",
	}
	TaskMessageType_value = map[string]int32{
		"TASK_MESSAGE_TYPE_UNSPECIFIED": 0,
		"TASK_MESSAGE_TYPE_START":       1,
		"TASK_MESSAGE_TYPE_PROGRESS":    2,
		"TASK_MESSAGE_TYPE_OUTPUT":      3,
		"TASK_MESSAGE_TYPE_COMPLETE":    4,
		"TASK_MESSAGE_TYPE_CANCEL":      5,
	}
)

func (x TaskMessageType) Enum() *TaskMessageType {
	p := new(TaskMessageType)
	*p = x
	return p
}

func (x TaskMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_data_proto_enumTypes[1].Descriptor()
}

func (TaskMessageType) Type() protoreflect.EnumType {
	return &file_transport_data_proto_enumTypes[1]
}

func (x TaskMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskMessageType.Descriptor instead.
func (TaskMessageType) EnumDescriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{1}
}

type ConfigSyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StewardId      string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	CurrentVersion string                 `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // steward's current config version (for delta)
	Modules        []string               `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`                                     // optional: specific modules to sync
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigSyncRequest) Reset() {
	*x = ConfigSyncRequest{}
	mi := &file_transport_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSyncRequest) ProtoMessage() {}

func (x *ConfigSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSyncRequest.ProtoReflect.Descriptor instead.
func (*ConfigSyncRequest) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigSyncRequest) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *ConfigSyncRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *ConfigSyncRequest) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ConfigChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // chunk of signed config data
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	ConfigId      string                 `protobuf:"bytes,5,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChunk) Reset() {
	*x = ConfigChunk{}
	mi := &file_transport_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChunk) ProtoMessage() {}

func (x *ConfigChunk) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChunk.ProtoReflect.Descriptor instead.
func (*ConfigChunk) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConfigChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ConfigChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ConfigChunk) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigChunk) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

type DNAChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // chunk of DNA data
	ChunkIndex    int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	IsDelta       bool                   `protobuf:"varint,6,opt,name=is_delta,json=isDelta,proto3" json:"is_delta,omitempty"` // true = delta update, false = full snapshot
	DnaHash       string                 `protobuf:"bytes,7,opt,name=dna_hash,json=dnaHash,proto3" json:"dna_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNAChunk) Reset() {
	*x = DNAChunk{}
	mi := &file_transport_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNAChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNAChunk) ProtoMessage() {}

func (x *DNAChunk) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNAChunk.ProtoReflect.Descriptor instead.
func (*DNAChunk) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{2}
}

func (x *DNAChunk) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *DNAChunk) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DNAChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DNAChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *DNAChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *DNAChunk) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

func (x *DNAChunk) GetDnaHash() string {
	if x != nil {
		return x.DnaHash
	}
	return ""
}

type DNASyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewHash       string                 `protobuf:"bytes,3,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"` // controller's computed hash after applying
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNASyncResponse) Reset() {
	*x = DNASyncResponse{}
	mi := &file_transport_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNASyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNASyncResponse) ProtoMessage() {}

func (x *DNASyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNASyncResponse.ProtoReflect.Descriptor instead.
func (*DNASyncResponse) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{3}
}

func (x *DNASyncResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DNASyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DNASyncResponse) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

type BulkChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	TransferType  TransferType           `protobuf:"varint,2,opt,name=transfer_type,json=transferType,proto3,enum=cfgms.transport.TransferType" json:"transfer_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	IsLast        bool                   `protobuf:"varint,6,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkChunk) Reset() {
	*x = BulkChunk{}
	mi := &file_transport_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkChunk) ProtoMessage() {}

func (x *BulkChunk) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkChunk.ProtoReflect.Descriptor instead.
func (*BulkChunk) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{4}
}

func (x *BulkChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *BulkChunk) GetTransferType() TransferType {
	if x != nil {
		return x.TransferType
	}
	return TransferType_TRANSFER_TYPE_UNSPECIFIED
}

func (x *BulkChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BulkChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BulkChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *BulkChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *BulkChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TaskMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          TaskMessageType        `protobuf:"varint,2,opt,name=type,proto3,enum=cfgms.transport.TaskMessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMessage) Reset() {
	*x = TaskMessage{}
	mi := &file_transport_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMessage) ProtoMessage() {}

func (x *TaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMessage.ProtoReflect.Descriptor instead.
func (*TaskMessage) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{5}
}

func (x *TaskMessage) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskMessage) GetType() TaskMessageType {
	if x != nil {
		return x.Type
	}
	return TaskMessageType_TASK_MESSAGE_TYPE_UNSPECIFIED
}

func (x *TaskMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TerminalData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // raw terminal I/O
	IsResize      bool                   `protobuf:"varint,3,opt,name=is_resize,json=isResize,proto3" json:"is_resize,omitempty"`
	Rows          int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalData) Reset() {
	*x = TerminalData{}
	mi := &file_transport_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalData) ProtoMessage() {}

func (x *TerminalData) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalData.ProtoReflect.Descriptor instead.
func (*TerminalData) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalData) GetIsResize() bool {
	if x != nil {
		return x.IsResize
	}
	return false
}

func (x *TerminalData) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalData) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Level         Severity               `protobuf:"varint,2,opt,name=level,proto3,enum=cfgms.transport.Severity" json:"level,omitempty"` // reuses Severity from control.proto (same package)
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_transport_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *LogEntry) GetLevel() Severity {
	if x != nil {
		return x.Level
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LogStreamResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntriesReceived int64                  `protobuf:"varint,1,opt,name=entries_received,json=entriesReceived,proto3" json:"entries_received,omitempty"`
	Acknowledged    bool                   `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_transport_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_transport_data_proto_rawDescGZIP(), []int{8}
}

func (x *LogStreamResponse) GetEntriesReceived() int64 {
	if x != nil {
		return x.EntriesReceived
	}
	return 0
}

func (x *LogStreamResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_transport_data_proto protoreflect.FileDescriptor

const file_transport_data_proto_rawDesc = "" +
	"\n" +
	"\x14transport/data.proto\x12\x0fcfgms.transport\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17transport/control.proto\"u\n" +
	"\x11ConfigSyncRequest\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\x12\x18\n" +
	"\amodules\x18\x03 \x03(\tR\amodules\"\x9c\x01\n" +
	"\vConfigChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1b\n" +
	"\tconfig_id\x18\x05 \x01(\tR\bconfigId\"\xd4\x01\n" +
	"\bDNAChunk\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x05 \x01(\x05R\vtotalChunks\x12\x19\n" +
	"\bis_delta\x18\x06 \x01(\bR\aisDelta\x12\x19\n" +
	"\bdna_hash\x18\a \x01(\tR\adnaHash\"b\n" +
	"\x0fDNASyncResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bnew_hash\x18\x03 \x01(\tR\anewHash\"\xd7\x02\n" +
	"\tBulkChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12B\n" +
	"\rtransfer_type\x18\x02 \x01(\x0e2\x1d.cfgms.transport.TransferTypeR\ftransferType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12\x17\n" +
	"\ais_last\x18\x06 \x01(\bR\x06isLast\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.cfgms.transport.BulkChunk.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\vTaskMessage\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .cfgms.transport.TaskMessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x86\x01\n" +
	"\fTerminalData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tis_resize\x18\x03 \x01(\bR\bisResize\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\x05R\x04cols\"\xa8\x02\n" +
	"\bLogEntry\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12/\n" +
	"\x05level\x18\x02 \x01(\x0e2\x19.cfgms.transport.SeverityR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\x06fields\x18\x05 \x03(\v2%.cfgms.transport.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x11LogStreamResponse\x12)\n" +
	"\x10entries_received\x18\x01 \x01(\x03R\x0fentriesReceived\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged*\x99\x01\n" +
	"\fTransferType\x12\x1d\n" +
	"\x19TRANSFER_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRANSFER_TYPE_PACKAGE\x10\x01\x12\x18\n" +
	"\x14TRANSFER_TYPE_SCRIPT\x10\x02\x12\x1b\n" +
	"\x17TRANSFER_TYPE_LOG_BATCH\x10\x03\x12\x18\n" +
	"\x14TRANSFER_TYPE_BINARY\x10\x04*\xcd\x01\n" +
	"\x0fTaskMessageType\x12!\n" +
	"\x1dTASK_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TASK_MESSAGE_TYPE_START\x10\x01\x12\x1e\n" +
	"\x1aTASK_MESSAGE_TYPE_PROGRESS\x10\x02\x12\x1c\n" +
	"\x18TASK_MESSAGE_TYPE_OUTPUT\x10\x03\x12\x1e\n" +
	"\x1aTASK_MESSAGE_TYPE_COMPLETE\x10\x04\x12\x1c\n" +
	"\x18TASK_MESSAGE_TYPE_CANCEL\x10\x05B,Z*github.com/cfgis/cfgms/api/proto/transportb\x06proto3"

var (
	file_transport_data_proto_rawDescOnce sync.Once
	file_transport_data_proto_rawDescData []byte
)

func file_transport_data_proto_rawDescGZIP() []byte {
	file_transport_data_proto_rawDescOnce.Do(func() {
		file_transport_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_data_proto_rawDesc), len(file_transport_data_proto_rawDesc)))
	})
	return file_transport_data_proto_rawDescData
}

var file_transport_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transport_data_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_transport_data_proto_goTypes = []any{
	(TransferType)(0),             // 0: cfgms.transport.TransferType
	(TaskMessageType)(0),          // 1: cfgms.transport.TaskMessageType
	(*ConfigSyncRequest)(nil),     // 2: cfgms.transport.ConfigSyncRequest
	(*ConfigChunk)(nil),           // 3: cfgms.transport.ConfigChunk
	(*DNAChunk)(nil),              // 4: cfgms.transport.DNAChunk
	(*DNASyncResponse)(nil),       // 5: cfgms.transport.DNASyncResponse
	(*BulkChunk)(nil),             // 6: cfgms.transport.BulkChunk
	(*TaskMessage)(nil),           // 7: cfgms.transport.TaskMessage
	(*TerminalData)(nil),          // 8: cfgms.transport.TerminalData
	(*LogEntry)(nil),              // 9: cfgms.transport.LogEntry
	(*LogStreamResponse)(nil),     // 10: cfgms.transport.LogStreamResponse
	nil,                           // 11: cfgms.transport.BulkChunk.MetadataEntry
	nil,                           // 12: cfgms.transport.LogEntry.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(Severity)(0),                 // 14: cfgms.transport.Severity
}
var file_transport_data_proto_depIdxs = []int32{
	0,  // 0: cfgms.transport.BulkChunk.transfer_type:type_name -> cfgms.transport.TransferType
	11, // 1: cfgms.transport.BulkChunk.metadata:type_name -> cfgms.transport.BulkChunk.MetadataEntry
	1,  // 2: cfgms.transport.TaskMessage.type:type_name -> cfgms.transport.TaskMessageType
	13, // 3: cfgms.transport.TaskMessage.timestamp:type_name -> google.protobuf.Timestamp
	14, // 4: cfgms.transport.LogEntry.level:type_name -> cfgms.transport.Severity
	13, // 5: cfgms.transport.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	12, // 6: cfgms.transport.LogEntry.fields:type_name -> cfgms.transport.LogEntry.FieldsEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_transport_data_proto_init() }
func file_transport_data_proto_init() {
	if File_transport_data_proto != nil {
		return
	}
	file_transport_control_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_data_proto_rawDesc), len(file_transport_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_data_proto_goTypes,
		DependencyIndexes: file_transport_data_proto_depIdxs,
		EnumInfos:         file_transport_data_proto_enumTypes,
		MessageInfos:      file_transport_data_proto_msgTypes,
	}.Build()
	File_transport_data_proto = out.File
	file_transport_data_proto_goTypes = nil
	file_transport_data_proto_depIdxs = nil
}
