// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: transport/transport.proto

package transport

import (
	context "context"
	controller "github.com/cfgis/cfgms/api/proto/controller"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StewardTransport_Register_FullMethodName       = "/cfgms.transport.StewardTransport/Register"
	StewardTransport_Ping_FullMethodName           = "/cfgms.transport.StewardTransport/Ping"
	StewardTransport_ControlChannel_FullMethodName = "/cfgms.transport.StewardTransport/ControlChannel"
	StewardTransport_SyncConfig_FullMethodName     = "/cfgms.transport.StewardTransport/SyncConfig"
	StewardTransport_SyncDNA_FullMethodName        = "/cfgms.transport.StewardTransport/SyncDNA"
	StewardTransport_BulkTransfer_FullMethodName   = "/cfgms.transport.StewardTransport/BulkTransfer"
	StewardTransport_TaskStream_FullMethodName     = "/cfgms.transport.StewardTransport/TaskStream"
	StewardTransport_Terminal_FullMethodName       = "/cfgms.transport.StewardTransport/Terminal"
	StewardTransport_LogStream_FullMethodName      = "/cfgms.transport.StewardTransport/LogStream"
)

// StewardTransportClient is the client API for StewardTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StewardTransport is the unified controller-steward communication service.
//
// All RPCs run over a single QUIC connection per steward. The ControlChannel
// bidi stream carries C2 traffic (commands, events, heartbeats, responses).
// Data transfer RPCs carry config sync, DNA sync, and bulk transfers.
type StewardTransportClient interface {
	// Register authenticates a steward and establishes identity.
	// Called once on first connection or after credential rotation.
	Register(ctx context.Context, in *controller.RegisterRequest, opts ...grpc.CallOption) (*controller.RegisterResponse, error)
	// Ping is a lightweight health check / latency probe.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// ControlChannel is a persistent bidirectional stream for C2 traffic.
	// Steward opens on connect, stays open for connection lifetime.
	// Controller pushes Commands; steward sends Events, Heartbeats, Responses.
	ControlChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error)
	// SyncConfig streams configuration from controller to steward.
	SyncConfig(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigChunk], error)
	// SyncDNA streams DNA data from steward to controller.
	SyncDNA(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DNAChunk, DNASyncResponse], error)
	// BulkTransfer handles bidirectional bulk data (packages, scripts, logs).
	BulkTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BulkChunk, BulkChunk], error)
	// TaskStream provides bidirectional task execution updates.
	TaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskMessage, TaskMessage], error)
	// Terminal provides interactive terminal access to a steward.
	Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalData, TerminalData], error)
	// LogStream streams logs from steward to controller.
	LogStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, LogStreamResponse], error)
}

type stewardTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewStewardTransportClient(cc grpc.ClientConnInterface) StewardTransportClient {
	return &stewardTransportClient{cc}
}

func (c *stewardTransportClient) Register(ctx context.Context, in *controller.RegisterRequest, opts ...grpc.CallOption) (*controller.RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(controller.RegisterResponse)
	err := c.cc.Invoke(ctx, StewardTransport_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stewardTransportClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, StewardTransport_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stewardTransportClient) ControlChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StewardTransport_ServiceDesc.Streams[0], StewardTransport_ControlChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_ControlChannelClient = grpc.BidiStreamingClient[ControlMessage, ControlMessage]

func (c *stewardTransportClient) SyncConfig(ctx context.Context, in *ConfigSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StewardTransport_ServiceDesc.Streams[1], StewardTransport_SyncConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigSyncRequest, ConfigChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_SyncConfigClient = grpc.ServerStreamingClient[ConfigChunk]

func (c *stewardTransportClient) SyncDNA(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DNAChunk, DNASyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StewardTransport_ServiceDesc.Streams[2], StewardTransport_SyncDNA_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DNAChunk, DNASyncResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_SyncDNAClient = grpc.ClientStreamingClient[DNAChunk, DNASyncResponse]

func (c *stewardTransportClient) BulkTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BulkChunk, BulkChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StewardTransport_ServiceDesc.Streams[3], StewardTransport_BulkTransfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BulkChunk, BulkChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_BulkTransferClient = grpc.BidiStreamingClient[BulkChunk, BulkChunk]

func (c *stewardTransportClient) TaskStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskMessage, TaskMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StewardTransport_ServiceDesc.Streams[4], StewardTransport_TaskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskMessage, TaskMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_TaskStreamClient = grpc.BidiStreamingClient[TaskMessage, TaskMessage]

func (c *stewardTransportClient) Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalData, TerminalData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StewardTransport_ServiceDesc.Streams[5], StewardTransport_Terminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalData, TerminalData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_TerminalClient = grpc.BidiStreamingClient[TerminalData, TerminalData]

func (c *stewardTransportClient) LogStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StewardTransport_ServiceDesc.Streams[6], StewardTransport_LogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEntry, LogStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_LogStreamClient = grpc.ClientStreamingClient[LogEntry, LogStreamResponse]

// StewardTransportServer is the server API for StewardTransport service.
// All implementations must embed UnimplementedStewardTransportServer
// for forward compatibility.
//
// StewardTransport is the unified controller-steward communication service.
//
// All RPCs run over a single QUIC connection per steward. The ControlChannel
// bidi stream carries C2 traffic (commands, events, heartbeats, responses).
// Data transfer RPCs carry config sync, DNA sync, and bulk transfers.
type StewardTransportServer interface {
	// Register authenticates a steward and establishes identity.
	// Called once on first connection or after credential rotation.
	Register(context.Context, *controller.RegisterRequest) (*controller.RegisterResponse, error)
	// Ping is a lightweight health check / latency probe.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// ControlChannel is a persistent bidirectional stream for C2 traffic.
	// Steward opens on connect, stays open for connection lifetime.
	// Controller pushes Commands; steward sends Events, Heartbeats, Responses.
	ControlChannel(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error
	// SyncConfig streams configuration from controller to steward.
	SyncConfig(*ConfigSyncRequest, grpc.ServerStreamingServer[ConfigChunk]) error
	// SyncDNA streams DNA data from steward to controller.
	SyncDNA(grpc.ClientStreamingServer[DNAChunk, DNASyncResponse]) error
	// BulkTransfer handles bidirectional bulk data (packages, scripts, logs).
	BulkTransfer(grpc.BidiStreamingServer[BulkChunk, BulkChunk]) error
	// TaskStream provides bidirectional task execution updates.
	TaskStream(grpc.BidiStreamingServer[TaskMessage, TaskMessage]) error
	// Terminal provides interactive terminal access to a steward.
	Terminal(grpc.BidiStreamingServer[TerminalData, TerminalData]) error
	// LogStream streams logs from steward to controller.
	LogStream(grpc.ClientStreamingServer[LogEntry, LogStreamResponse]) error
	mustEmbedUnimplementedStewardTransportServer()
}

// UnimplementedStewardTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStewardTransportServer struct{}

func (UnimplementedStewardTransportServer) Register(context.Context, *controller.RegisterRequest) (*controller.RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedStewardTransportServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStewardTransportServer) ControlChannel(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method ControlChannel not implemented")
}
func (UnimplementedStewardTransportServer) SyncConfig(*ConfigSyncRequest, grpc.ServerStreamingServer[ConfigChunk]) error {
	return status.Error(codes.Unimplemented, "method SyncConfig not implemented")
}
func (UnimplementedStewardTransportServer) SyncDNA(grpc.ClientStreamingServer[DNAChunk, DNASyncResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncDNA not implemented")
}
func (UnimplementedStewardTransportServer) BulkTransfer(grpc.BidiStreamingServer[BulkChunk, BulkChunk]) error {
	return status.Error(codes.Unimplemented, "method BulkTransfer not implemented")
}
func (UnimplementedStewardTransportServer) TaskStream(grpc.BidiStreamingServer[TaskMessage, TaskMessage]) error {
	return status.Error(codes.Unimplemented, "method TaskStream not implemented")
}
func (UnimplementedStewardTransportServer) Terminal(grpc.BidiStreamingServer[TerminalData, TerminalData]) error {
	return status.Error(codes.Unimplemented, "method Terminal not implemented")
}
func (UnimplementedStewardTransportServer) LogStream(grpc.ClientStreamingServer[LogEntry, LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method LogStream not implemented")
}
func (UnimplementedStewardTransportServer) mustEmbedUnimplementedStewardTransportServer() {}
func (UnimplementedStewardTransportServer) testEmbeddedByValue()                          {}

// UnsafeStewardTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StewardTransportServer will
// result in compilation errors.
type UnsafeStewardTransportServer interface {
	mustEmbedUnimplementedStewardTransportServer()
}

func RegisterStewardTransportServer(s grpc.ServiceRegistrar, srv StewardTransportServer) {
	// If the following call panics, it indicates UnimplementedStewardTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StewardTransport_ServiceDesc, srv)
}

func _StewardTransport_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(controller.RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StewardTransportServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StewardTransport_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StewardTransportServer).Register(ctx, req.(*controller.RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StewardTransport_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StewardTransportServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StewardTransport_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StewardTransportServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StewardTransport_ControlChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StewardTransportServer).ControlChannel(&grpc.GenericServerStream[ControlMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_ControlChannelServer = grpc.BidiStreamingServer[ControlMessage, ControlMessage]

func _StewardTransport_SyncConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigSyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StewardTransportServer).SyncConfig(m, &grpc.GenericServerStream[ConfigSyncRequest, ConfigChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_SyncConfigServer = grpc.ServerStreamingServer[ConfigChunk]

func _StewardTransport_SyncDNA_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StewardTransportServer).SyncDNA(&grpc.GenericServerStream[DNAChunk, DNASyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_SyncDNAServer = grpc.ClientStreamingServer[DNAChunk, DNASyncResponse]

func _StewardTransport_BulkTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StewardTransportServer).BulkTransfer(&grpc.GenericServerStream[BulkChunk, BulkChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_BulkTransferServer = grpc.BidiStreamingServer[BulkChunk, BulkChunk]

func _StewardTransport_TaskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StewardTransportServer).TaskStream(&grpc.GenericServerStream[TaskMessage, TaskMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_TaskStreamServer = grpc.BidiStreamingServer[TaskMessage, TaskMessage]

func _StewardTransport_Terminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StewardTransportServer).Terminal(&grpc.GenericServerStream[TerminalData, TerminalData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_TerminalServer = grpc.BidiStreamingServer[TerminalData, TerminalData]

func _StewardTransport_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StewardTransportServer).LogStream(&grpc.GenericServerStream[LogEntry, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StewardTransport_LogStreamServer = grpc.ClientStreamingServer[LogEntry, LogStreamResponse]

// StewardTransport_ServiceDesc is the grpc.ServiceDesc for StewardTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StewardTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cfgms.transport.StewardTransport",
	HandlerType: (*StewardTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _StewardTransport_Register_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StewardTransport_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlChannel",
			Handler:       _StewardTransport_ControlChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncConfig",
			Handler:       _StewardTransport_SyncConfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncDNA",
			Handler:       _StewardTransport_SyncDNA_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BulkTransfer",
			Handler:       _StewardTransport_BulkTransfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TaskStream",
			Handler:       _StewardTransport_TaskStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Terminal",
			Handler:       _StewardTransport_Terminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LogStream",
			Handler:       _StewardTransport_LogStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "transport/transport.proto",
}
