// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: transport/transport.proto

package transport

import (
	controller "github.com/cfgis/cfgms/api/proto/controller"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest is a lightweight health check.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // nanosecond timestamp for latency measurement
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_transport_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_transport_transport_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *PingRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// PingResponse echoes the request timestamp for RTT calculation.
type PingResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestTimestampNs  int64                  `protobuf:"varint,1,opt,name=request_timestamp_ns,json=requestTimestampNs,proto3" json:"request_timestamp_ns,omitempty"`
	ResponseTimestampNs int64                  `protobuf:"varint,2,opt,name=response_timestamp_ns,json=responseTimestampNs,proto3" json:"response_timestamp_ns,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_transport_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_transport_transport_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetRequestTimestampNs() int64 {
	if x != nil {
		return x.RequestTimestampNs
	}
	return 0
}

func (x *PingResponse) GetResponseTimestampNs() int64 {
	if x != nil {
		return x.ResponseTimestampNs
	}
	return 0
}

var File_transport_transport_proto protoreflect.FileDescriptor

const file_transport_transport_proto_rawDesc = "" +
	"\n" +
	"\x19transport/transport.proto\x12\x0fcfgms.transport\x1a\x17transport/control.proto\x1a\x14transport/data.proto\x1a\x1bcontroller/controller.proto\"O\n" +
	"\vPingRequest\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\"t\n" +
	"\fPingResponse\x120\n" +
	"\x14request_timestamp_ns\x18\x01 \x01(\x03R\x12requestTimestampNs\x122\n" +
	"\x15response_timestamp_ns\x18\x02 \x01(\x03R\x13responseTimestampNs2\xdc\x05\n" +
	"\x10StewardTransport\x12Y\n" +
	"\bRegister\x12%.cfgms.api.controller.RegisterRequest\x1a&.cfgms.api.controller.RegisterResponse\x12C\n" +
	"\x04Ping\x12\x1c.cfgms.transport.PingRequest\x1a\x1d.cfgms.transport.PingResponse\x12V\n" +
	"\x0eControlChannel\x12\x1f.cfgms.transport.ControlMessage\x1a\x1f.cfgms.transport.ControlMessage(\x010\x01\x12P\n" +
	"\n" +
	"SyncConfig\x12\".cfgms.transport.ConfigSyncRequest\x1a\x1c.cfgms.transport.ConfigChunk0\x01\x12H\n" +
	"\aSyncDNA\x12\x19.cfgms.transport.DNAChunk\x1a .cfgms.transport.DNASyncResponse(\x01\x12J\n" +
	"\fBulkTransfer\x12\x1a.cfgms.transport.BulkChunk\x1a\x1a.cfgms.transport.BulkChunk(\x010\x01\x12L\n" +
	"\n" +
	"TaskStream\x12\x1c.cfgms.transport.TaskMessage\x1a\x1c.cfgms.transport.TaskMessage(\x010\x01\x12L\n" +
	"\bTerminal\x12\x1d.cfgms.transport.TerminalData\x1a\x1d.cfgms.transport.TerminalData(\x010\x01\x12L\n" +
	"\tLogStream\x12\x19.cfgms.transport.LogEntry\x1a\".cfgms.transport.LogStreamResponse(\x01B,Z*github.com/cfgis/cfgms/api/proto/transportb\x06proto3"

var (
	file_transport_transport_proto_rawDescOnce sync.Once
	file_transport_transport_proto_rawDescData []byte
)

func file_transport_transport_proto_rawDescGZIP() []byte {
	file_transport_transport_proto_rawDescOnce.Do(func() {
		file_transport_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_transport_proto_rawDesc), len(file_transport_transport_proto_rawDesc)))
	})
	return file_transport_transport_proto_rawDescData
}

var file_transport_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_transport_proto_goTypes = []any{
	(*PingRequest)(nil),                 // 0: cfgms.transport.PingRequest
	(*PingResponse)(nil),                // 1: cfgms.transport.PingResponse
	(*controller.RegisterRequest)(nil),  // 2: cfgms.api.controller.RegisterRequest
	(*ControlMessage)(nil),              // 3: cfgms.transport.ControlMessage
	(*ConfigSyncRequest)(nil),           // 4: cfgms.transport.ConfigSyncRequest
	(*DNAChunk)(nil),                    // 5: cfgms.transport.DNAChunk
	(*BulkChunk)(nil),                   // 6: cfgms.transport.BulkChunk
	(*TaskMessage)(nil),                 // 7: cfgms.transport.TaskMessage
	(*TerminalData)(nil),                // 8: cfgms.transport.TerminalData
	(*LogEntry)(nil),                    // 9: cfgms.transport.LogEntry
	(*controller.RegisterResponse)(nil), // 10: cfgms.api.controller.RegisterResponse
	(*ConfigChunk)(nil),                 // 11: cfgms.transport.ConfigChunk
	(*DNASyncResponse)(nil),             // 12: cfgms.transport.DNASyncResponse
	(*LogStreamResponse)(nil),           // 13: cfgms.transport.LogStreamResponse
}
var file_transport_transport_proto_depIdxs = []int32{
	2,  // 0: cfgms.transport.StewardTransport.Register:input_type -> cfgms.api.controller.RegisterRequest
	0,  // 1: cfgms.transport.StewardTransport.Ping:input_type -> cfgms.transport.PingRequest
	3,  // 2: cfgms.transport.StewardTransport.ControlChannel:input_type -> cfgms.transport.ControlMessage
	4,  // 3: cfgms.transport.StewardTransport.SyncConfig:input_type -> cfgms.transport.ConfigSyncRequest
	5,  // 4: cfgms.transport.StewardTransport.SyncDNA:input_type -> cfgms.transport.DNAChunk
	6,  // 5: cfgms.transport.StewardTransport.BulkTransfer:input_type -> cfgms.transport.BulkChunk
	7,  // 6: cfgms.transport.StewardTransport.TaskStream:input_type -> cfgms.transport.TaskMessage
	8,  // 7: cfgms.transport.StewardTransport.Terminal:input_type -> cfgms.transport.TerminalData
	9,  // 8: cfgms.transport.StewardTransport.LogStream:input_type -> cfgms.transport.LogEntry
	10, // 9: cfgms.transport.StewardTransport.Register:output_type -> cfgms.api.controller.RegisterResponse
	1,  // 10: cfgms.transport.StewardTransport.Ping:output_type -> cfgms.transport.PingResponse
	3,  // 11: cfgms.transport.StewardTransport.ControlChannel:output_type -> cfgms.transport.ControlMessage
	11, // 12: cfgms.transport.StewardTransport.SyncConfig:output_type -> cfgms.transport.ConfigChunk
	12, // 13: cfgms.transport.StewardTransport.SyncDNA:output_type -> cfgms.transport.DNASyncResponse
	6,  // 14: cfgms.transport.StewardTransport.BulkTransfer:output_type -> cfgms.transport.BulkChunk
	7,  // 15: cfgms.transport.StewardTransport.TaskStream:output_type -> cfgms.transport.TaskMessage
	8,  // 16: cfgms.transport.StewardTransport.Terminal:output_type -> cfgms.transport.TerminalData
	13, // 17: cfgms.transport.StewardTransport.LogStream:output_type -> cfgms.transport.LogStreamResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_transport_transport_proto_init() }
func file_transport_transport_proto_init() {
	if File_transport_transport_proto != nil {
		return
	}
	file_transport_control_proto_init()
	file_transport_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_transport_proto_rawDesc), len(file_transport_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_transport_proto_goTypes,
		DependencyIndexes: file_transport_transport_proto_depIdxs,
		MessageInfos:      file_transport_transport_proto_msgTypes,
	}.Build()
	File_transport_transport_proto = out.File
	file_transport_transport_proto_goTypes = nil
	file_transport_transport_proto_depIdxs = nil
}
