// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Jordan Ritz
package api

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/gorilla/mux"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// routeEntry records one {method, path-template} pair from a mux.Router.Walk.
type routeEntry struct {
	method string
	path   string
}

func (r routeEntry) String() string { return r.method + " " + r.path }

// walkRoutes returns all {method, path-template} pairs registered on router, sorted.
func walkRoutes(t *testing.T, router *mux.Router) []routeEntry {
	t.Helper()
	var entries []routeEntry
	err := router.Walk(func(route *mux.Route, _ *mux.Router, _ []*mux.Route) error {
		tpl, err := route.GetPathTemplate()
		if err != nil {
			return nil // skip routes without a path template (e.g. MethodNotAllowed)
		}
		methods, err := route.GetMethods()
		if err != nil || len(methods) == 0 {
			// Route has no explicit methods — record with empty method marker.
			entries = append(entries, routeEntry{"*", tpl})
			return nil
		}
		for _, m := range methods {
			entries = append(entries, routeEntry{m, tpl})
		}
		return nil
	})
	require.NoError(t, err)
	sort.Slice(entries, func(i, j int) bool {
		si, sj := entries[i].String(), entries[j].String()
		return si < sj
	})
	return entries
}

// goldenRouteTable is the canonical {method, path} set produced by setupRouter after the
// refactor. Generated by running walkRoutes (via TestGetRouteTableForGolden) on the
// refactored server; asserted on every test run to catch regressions.
// * entries are gorilla/mux PathPrefix subrouter prefix-routes (no explicit method).
var goldenRouteTable = []string{
	"* /",
	"* /api/v1",
	"* /api/v1/accounts",
	"* /api/v1/alerts",
	"* /api/v1/api-keys",
	"* /api/v1/cases",
	"* /api/v1/cases",
	"* /api/v1/cases",
	"* /api/v1/certificates",
	"* /api/v1/cluster",
	"* /api/v1/clusters",
	"* /api/v1/compliance",
	"* /api/v1/config",
	"* /api/v1/credential-requests",
	"* /api/v1/credential-requests",
	"* /api/v1/enrolment-tokens",
	"* /api/v1/entities",
	"* /api/v1/fleet",
	"* /api/v1/ha",
	"* /api/v1/installer/artifacts",
	"* /api/v1/installer/steward-binaries",
	"* /api/v1/jobs",
	"* /api/v1/modules/approvals",
	"* /api/v1/monitoring",
	"* /api/v1/operator-payload/sign",
	"* /api/v1/osquery",
	"* /api/v1/rbac",
	"* /api/v1/registration/tokens",
	"* /api/v1/roles",
	"* /api/v1/rollout",
	"* /api/v1/runs",
	"* /api/v1/scripts",
	"* /api/v1/signing-credential",
	"* /api/v1/stewards",
	"* /api/v1/stewards/upgrade",
	"* /api/v1/tenants",
	"* /api/v1/webauthn",
	"DELETE /api/v1/accounts/{username}",
	"DELETE /api/v1/api-keys/{id}",
	"DELETE /api/v1/cases/{id}/pins/{pin_id}",
	"DELETE /api/v1/installer/artifacts/{platform}/{arch}",
	"DELETE /api/v1/rbac/roles/{id}",
	"DELETE /api/v1/rbac/subjects/{id}/roles/{role_id}",
	"DELETE /api/v1/registration/ip-trust/{tenant_id}/{cidr:.+}",
	"DELETE /api/v1/registration/tokens/{token}",
	"DELETE /api/v1/roles/{name}",
	"DELETE /api/v1/runs/{run_id}",
	"DELETE /api/v1/sessions/{id}",
	"DELETE /api/v1/stewards/{id}",
	"DELETE /api/v1/stewards/{id}/config",
	"DELETE /api/v1/stewards/{id}/tags",
	"DELETE /api/v1/tenants/{id}/delete",
	"GET /api/v1/accounts",
	"GET /api/v1/accounts/{username}",
	"GET /api/v1/accounts/{username}/certs",
	"GET /api/v1/accounts/{username}/webauthn/credentials",
	"GET /api/v1/api-keys",
	"GET /api/v1/api-keys/{id}",
	"GET /api/v1/audit/entries",
	"GET /api/v1/cases",
	"GET /api/v1/cases/{id}",
	"GET /api/v1/cases/{id}/watch",
	"GET /api/v1/certificates",
	"GET /api/v1/certificates/revocation-manifest",
	"GET /api/v1/certificates/{serial}",
	"GET /api/v1/cli-login/{id}",
	"GET /api/v1/clusters",
	"GET /api/v1/clusters/{name}",
	"GET /api/v1/clusters/{name}/reconciliation",
	"GET /api/v1/compliance/summary",
	"GET /api/v1/config/push/{id}",
	"GET /api/v1/configs",
	"GET /api/v1/configs/{id}/deployments",
	"GET /api/v1/credential-requests",
	"GET /api/v1/credential-requests/orphaned",
	"GET /api/v1/entities",
	"GET /api/v1/entities/drifted",
	"GET /api/v1/entities/timeline",
	"GET /api/v1/entities/{eid:.+}",
	"GET /api/v1/entities/{eid:.+}/desired-state",
	"GET /api/v1/entities/{eid:.+}/diff",
	"GET /api/v1/entities/{eid:.+}/drift",
	"GET /api/v1/entities/{eid:.+}/edges",
	"GET /api/v1/entities/{eid:.+}/history",
	"GET /api/v1/entities/{eid:.+}/neighborhood",
	"GET /api/v1/fleet/health",
	"GET /api/v1/ha/cluster",
	"GET /api/v1/ha/leader",
	"GET /api/v1/ha/nodes",
	"GET /api/v1/ha/status",
	"GET /api/v1/health",
	"GET /api/v1/installer/artifacts",
	"GET /api/v1/installer/artifacts/{platform}/{arch}",
	"GET /api/v1/installer/download/{platform}/{arch}",
	"GET /api/v1/installer/steward-binaries/{version}/{platform}/{arch}",
	"GET /api/v1/jobs",
	"GET /api/v1/jobs/{id}",
	"GET /api/v1/modules/approvals",
	"GET /api/v1/monitoring/anomalies",
	"GET /api/v1/monitoring/components/{component}/health",
	"GET /api/v1/monitoring/config",
	"GET /api/v1/monitoring/health",
	"GET /api/v1/public/steward-binaries/{version}/{platform}/{arch}",
	"GET /api/v1/raft/status",
	"GET /api/v1/rbac/permissions",
	"GET /api/v1/rbac/permissions/{id}",
	"GET /api/v1/rbac/roles",
	"GET /api/v1/rbac/roles/{id}",
	"GET /api/v1/rbac/subjects/{id}/roles",
	"GET /api/v1/ready",
	"GET /api/v1/registration/approve-by-cidr/preview",
	"GET /api/v1/registration/ip-trust",
	"GET /api/v1/registration/pending",
	"GET /api/v1/registration/status/{pending_id}",
	"GET /api/v1/registration/tokens",
	"GET /api/v1/registration/tokens/{token}",
	"GET /api/v1/roles",
	"GET /api/v1/roles/{name}",
	"GET /api/v1/rollout/{rollout_id}",
	"GET /api/v1/runs",
	"GET /api/v1/runs/{run_id}",
	"GET /api/v1/runs/{run_id}/jobs",
	"GET /api/v1/scripts",
	"GET /api/v1/scripts/{id}",
	"GET /api/v1/sessions",
	"GET /api/v1/stewards",
	"GET /api/v1/stewards/connections/all",
	"GET /api/v1/stewards/refresh/pending",
	"GET /api/v1/stewards/upgrade/{upgrade_id}",
	"GET /api/v1/stewards/{id}",
	"GET /api/v1/stewards/{id}/compliance",
	"GET /api/v1/stewards/{id}/compliance/report",
	"GET /api/v1/stewards/{id}/config",
	"GET /api/v1/stewards/{id}/config/effective",
	"GET /api/v1/stewards/{id}/connection",
	"GET /api/v1/stewards/{id}/dna",
	"GET /api/v1/stewards/{id}/logs",
	"GET /api/v1/stewards/{id}/modules",
	"GET /api/v1/stewards/{id}/reboot-window",
	"GET /api/v1/stewards/{id}/scripts/executions",
	"GET /api/v1/stewards/{id}/scripts/executions/{execution_id}",
	"GET /api/v1/stewards/{id}/scripts/metrics",
	"GET /api/v1/stewards/{id}/scripts/status",
	"GET /api/v1/stewards/{id}/tags",
	"GET /api/v1/tenants",
	"GET /api/v1/tenants/{id}",
	"GET /api/v1/tenants/{id}/access-grants",
	"GET /api/v1/tenants/{id}/delete",
	"GET /api/v1/tenants/{tenant_id}/reboot-window",
	"GET /api/v1/tenants/{tenant_path:.+}/assurance-policy",
	"GET /api/v1/tenants/{tenant_path:.+}/refresh-policy",
	"GET /api/v1/terminal/ws/{steward_id}",
	"GET /api/v1/web/csrf",
	"OPTIONS /api/v1/health",
	"OPTIONS /api/v1/ready",
	"OPTIONS /api/v1/register",
	"OPTIONS /api/v1/stewards/{device_id}/refresh/challenge",
	"OPTIONS /api/v1/stewards/{device_id}/refresh/complete",
	"PATCH /api/v1/stewards/{id}/visibility",
	"POST /api/v1/accounts",
	"POST /api/v1/accounts/{username}/certs/bind",
	"POST /api/v1/accounts/{username}/certs/revoke/{serial}",
	"POST /api/v1/accounts/{username}/certs/rotate/{old_serial}",
	"POST /api/v1/accounts/{username}/enrollment-link/revoke",
	"POST /api/v1/accounts/{username}/webauthn/register/begin",
	"POST /api/v1/accounts/{username}/webauthn/register/finish",
	"POST /api/v1/accounts/{username}/webauthn/revoke/{credential_id}",
	"POST /api/v1/alerts/{id}/acknowledge",
	"POST /api/v1/alerts/{id}/silence",
	"POST /api/v1/api-keys",
	"POST /api/v1/cases",
	"POST /api/v1/cases/intake-assist",
	"POST /api/v1/cases/{id}/pins",
	"POST /api/v1/certificates/provision",
	"POST /api/v1/certificates/signing/rotate",
	"POST /api/v1/certificates/{serial}/revoke",
	"POST /api/v1/cli-login/lodge",
	"POST /api/v1/cli-login/{id}/approve",
	"POST /api/v1/cli-login/{id}/collect",
	"POST /api/v1/cluster/nodes/{id}/decommission",
	"POST /api/v1/cluster/nodes/{id}/drain",
	"POST /api/v1/config/push",
	"POST /api/v1/credential-renewal",
	"POST /api/v1/credential-requests/lodge",
	"POST /api/v1/credential-requests/orphaned/{serial}/revoke",
	"POST /api/v1/credential-requests/{id}/approve",
	"POST /api/v1/credential-requests/{id}/cancel",
	"POST /api/v1/credential-requests/{id}/collect",
	"POST /api/v1/credential-requests/{id}/deny",
	"POST /api/v1/enrolment-tokens",
	"POST /api/v1/enrolment-tokens/{id}/revoke",
	"POST /api/v1/enrolment-tokens/{id}/revoke-issued-credentials",
	"POST /api/v1/entities/edges",
	"POST /api/v1/fleet/resolve",
	"POST /api/v1/installer/steward-binaries/{version}/{platform}/{arch}",
	"POST /api/v1/jobs",
	"POST /api/v1/modules/approvals/{address}/approve",
	"POST /api/v1/modules/approvals/{address}/reject",
	"POST /api/v1/operator-payload/sign/begin",
	"POST /api/v1/operator-payload/sign/finish",
	"POST /api/v1/osquery/query",
	"POST /api/v1/rbac/roles",
	"POST /api/v1/rbac/subjects/{id}/roles",
	"POST /api/v1/register",
	"POST /api/v1/registration/approve-all",
	"POST /api/v1/registration/approve-by-cidr",
	"POST /api/v1/registration/ip-trust",
	"POST /api/v1/registration/tokens",
	"POST /api/v1/registration/tokens/{tenant_id}/rotate",
	"POST /api/v1/registration/tokens/{token}/revoke",
	"POST /api/v1/registration/{id}/approve",
	"POST /api/v1/registration/{id}/deny",
	"POST /api/v1/roles",
	"POST /api/v1/rollout",
	"POST /api/v1/rollout/{rollout_id}/halt",
	"POST /api/v1/runs/command",
	"POST /api/v1/runs/script",
	"POST /api/v1/sessions",
	"POST /api/v1/signing-credential/request",
	"POST /api/v1/stewards/refresh/{pending_id}/approve",
	"POST /api/v1/stewards/refresh/{pending_id}/reject",
	"POST /api/v1/stewards/upgrade",
	"POST /api/v1/stewards/upgrade/{upgrade_id}/rollback",
	"POST /api/v1/stewards/{device_id}/refresh/challenge",
	"POST /api/v1/stewards/{device_id}/refresh/complete",
	"POST /api/v1/stewards/{id}/auth/refresh",
	"POST /api/v1/stewards/{id}/config/validate",
	"POST /api/v1/stewards/{id}/move",
	"POST /api/v1/stewards/{id}/scripts/executions/{execution_id}/retry",
	"POST /api/v1/stewards/{id}/tags",
	"POST /api/v1/tenants",
	"POST /api/v1/tenants/{id}/access-grants",
	"POST /api/v1/tenants/{id}/break-glass",
	"POST /api/v1/tenants/{id}/config-source/test",
	"POST /api/v1/tenants/{id}/delete",
	"POST /api/v1/tenants/{id}/delete/approve",
	"POST /api/v1/tenants/{id}/restore",
	"POST /api/v1/tenants/{id}/suspend",
	"POST /api/v1/web/logout",
	"POST /api/v1/web/passkey/enroll/begin",
	"POST /api/v1/web/passkey/enroll/finish",
	"POST /api/v1/web/passkey/login/begin",
	"POST /api/v1/web/passkey/login/finish",
	"POST /api/v1/webauthn/elevate/begin",
	"POST /api/v1/webauthn/elevate/finish",
	"POST /api/v1/webauthn/presence/begin",
	"POST /api/v1/webauthn/presence/finish",
	"POST /api/v1/webhooks/git-push",
	"PUT /api/v1/accounts/{username}",
	"PUT /api/v1/cases/{id}",
	"PUT /api/v1/installer/artifacts/{platform}/{arch}",
	"PUT /api/v1/rbac/roles/{id}",
	"PUT /api/v1/scripts/{id}/privilege",
	"PUT /api/v1/stewards/{id}/config",
	"PUT /api/v1/stewards/{id}/reboot-window",
	"PUT /api/v1/tenants/{id}",
	"PUT /api/v1/tenants/{tenant_id}/reboot-window",
	"PUT /api/v1/tenants/{tenant_path:.+}/assurance-policy",
	"PUT /api/v1/tenants/{tenant_path:.+}/refresh-policy",
}

// TestRouteTableParity verifies that the refactored self-registering route architecture
// produces exactly the same {method, path-template} set as the pre-refactor inline code.
// The golden fixture was generated by running walkRoutes against the pre-refactor server.
func TestRouteTableParity(t *testing.T) {
	s := setupRouteTestServer(t)
	router, ok := s.GetRouter().(*mux.Router)
	require.True(t, ok, "GetRouter must return *mux.Router")

	got := walkRoutes(t, router)
	var gotStrings []string
	for _, e := range got {
		gotStrings = append(gotStrings, e.String())
	}

	// Regeneration path: emit the fixture source for a copy/paste update when the
	// route table intentionally changes. Off by default so CI asserts, not prints.
	if os.Getenv("CFGMS_REGEN_GOLDEN_ROUTES") != "" {
		t.Log("\n" + formatGoldenRouteTable(got))
	}

	// Convert golden to sorted slice for comparison.
	golden := make([]string, len(goldenRouteTable))
	copy(golden, goldenRouteTable)
	sort.Strings(golden)

	assert.Equal(t, golden, gotStrings,
		"route table mismatch: routes added or removed during refactor")
}

// TestLiveDispatchAmbiguousPrefixes verifies that gorilla/mux routes requests to the
// correct handler even when two path prefixes share a string-prefix relationship
// (/clusters vs /cluster, /configs vs /config, /stewards/refresh/... vs /stewards/{id}).
// gorilla/mux v1.8 treats subrouters as matchers; a subrouter with no matching route
// causes the parent to backtrack and try the next route — so registration order among
// the extracted files does not affect correctness.
func TestLiveDispatchAmbiguousPrefixes(t *testing.T) {
	s := setupRouteTestServer(t)

	type routeCheck struct {
		method      string
		path        string
		description string
	}

	// All these routes must be FOUND (401/403 — auth ran but rejected — not 404/405).
	// 404 means routing failed; 405 means wrong method reached wrong subrouter.
	checks := []routeCheck{
		// /clusters prefix vs /cluster prefix
		{"GET", "/api/v1/clusters", "/clusters → clusters subrouter (not clusterRouter)"},
		{"GET", "/api/v1/clusters/mycluster", "/clusters/{name} → clusters subrouter"},
		{"POST", "/api/v1/cluster/nodes/x/drain", "/cluster/nodes/... → clusterRouter"},
		{"POST", "/api/v1/cluster/nodes/x/decommission", "/cluster/nodes/... → clusterRouter"},

		// /configs direct vs /config subrouter (cfgPush)
		{"GET", "/api/v1/configs", "/configs → direct api.Handle"},
		{"GET", "/api/v1/configs/abc/deployments", "/configs/{id}/deployments → direct api.Handle"},
		{"POST", "/api/v1/config/push", "/config/push → cfgPush subrouter"},
		{"GET", "/api/v1/config/push/abc", "/config/push/{id} → cfgPush subrouter"},

		// /stewards/refresh/... direct vs /stewards/{id} subrouter
		{"GET", "/api/v1/stewards/refresh/pending", "/stewards/refresh/pending → direct"},
		{"POST", "/api/v1/stewards/refresh/abc/approve", "/stewards/refresh/{id}/approve → direct"},
		{"POST", "/api/v1/stewards/refresh/abc/reject", "/stewards/refresh/{id}/reject → direct"},
		{"GET", "/api/v1/stewards/connections/all", "/stewards/connections/all → stewards subrouter"},
		{"GET", "/api/v1/stewards/mysw/connection", "/stewards/{id}/connection → stewards subrouter"},

		// /tenants/{id} vs /tenants/{tenant_path:.+}/refresh-policy
		{"GET", "/api/v1/tenants/root", "/tenants/{id} → tenants subrouter"},
		{"GET", "/api/v1/tenants/root/child/refresh-policy", "/tenants/.../refresh-policy → tenants subrouter"},
		{"PUT", "/api/v1/tenants/root/refresh-policy", "PUT /tenants/{tenant_path:.+}/refresh-policy"},

		// /stewards/upgrade vs /stewards/{id}
		{"POST", "/api/v1/stewards/upgrade", "/stewards/upgrade → stewardUpgrade subrouter"},
		{"GET", "/api/v1/stewards/upgrade/abc", "/stewards/upgrade/{id} → stewardUpgrade subrouter"},
	}

	for _, c := range checks {
		t.Run(c.description, func(t *testing.T) {
			req := httptest.NewRequest(c.method, c.path, nil)
			w := httptest.NewRecorder()
			s.GetRouter().ServeHTTP(w, req)
			resp := w.Result()
			assert.NotEqual(t, http.StatusNotFound, resp.StatusCode,
				"route not found: %s %s", c.method, c.path)
			assert.NotEqual(t, http.StatusMethodNotAllowed, resp.StatusCode,
				"method not allowed (routing failed): %s %s", c.method, c.path)
		})
	}
}

// TestClustersClusterRouterOrderIndependence verifies that /clusters and /cluster
// route correctly regardless of which registrar runs first. It builds two temporary
// routers with the two registrars in opposite orders and confirms each router routes
// both path families to the correct subrouter.
func TestClustersClusterRouterOrderIndependence(t *testing.T) {
	s := setupRouteTestServer(t)

	buildRouter := func(first, second RouteRegistrarFunc) *mux.Router {
		r := mux.NewRouter()
		api := r.PathPrefix("/api/v1").Subrouter()
		first(s, api)
		second(s, api)
		return r
	}

	for _, tc := range []struct {
		name   string
		router *mux.Router
	}{
		{"clusters-first", buildRouter(registerClusterRoutes, registerClusterLifecycleRoutes)},
		{"cluster-lifecycle-first", buildRouter(registerClusterLifecycleRoutes, registerClusterRoutes)},
	} {
		t.Run(tc.name, func(t *testing.T) {
			for _, check := range []struct{ method, path string }{
				{"GET", "/api/v1/clusters"},
				{"GET", "/api/v1/clusters/myname"},
				{"POST", "/api/v1/cluster/nodes/x/drain"},
				{"POST", "/api/v1/cluster/nodes/x/decommission"},
			} {
				req := httptest.NewRequest(check.method, check.path, nil)
				w := httptest.NewRecorder()
				tc.router.ServeHTTP(w, req)
				resp := w.Result()
				// 404 means routing broke; any other status (including 401, 405 on
				// wrong method to same route) means the route was found.
				assert.NotEqual(t, http.StatusNotFound, resp.StatusCode,
					"[%s] route not found: %s %s", tc.name, check.method, check.path)
			}
		})
	}
}

// TestIndependentRegistrars verifies that two unrelated features can each add a route
// via RegisterRoutes without editing server.go, route_registry.go, or each other.
// This is the retirement condition for the file-conflict-only dependency class (#2765→#2761).
func TestIndependentRegistrars(t *testing.T) {
	const (
		pathA = "/api/v1/test-feature-alpha/status"
		pathB = "/api/v1/test-feature-beta/status"
	)

	hitA := false
	hitB := false

	handlerA := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		hitA = true
		w.WriteHeader(http.StatusOK)
	})
	handlerB := http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		hitB = true
		w.WriteHeader(http.StatusOK)
	})

	// Build a minimal router that only contains the two test registrars,
	// without touching the real routeRegistrars slice.
	r := mux.NewRouter()
	api := r.PathPrefix("/api/v1").Subrouter()

	registrarA := RouteRegistrarFunc(func(_ *Server, api *mux.Router) {
		sub := api.PathPrefix("/test-feature-alpha").Subrouter()
		sub.Handle("/status", handlerA).Methods("GET")
	})
	registrarB := RouteRegistrarFunc(func(_ *Server, api *mux.Router) {
		sub := api.PathPrefix("/test-feature-beta").Subrouter()
		sub.Handle("/status", handlerB).Methods("GET")
	})

	// Mirrors what setupRouter's loop does with two independently-registered features.
	for _, reg := range []RouteRegistrarFunc{registrarA, registrarB} {
		reg(nil, api)
	}

	for _, tc := range []struct {
		path string
		hit  *bool
	}{
		{pathA, &hitA},
		{pathB, &hitB},
	} {
		req := httptest.NewRequest("GET", tc.path, nil)
		w := httptest.NewRecorder()
		r.ServeHTTP(w, req)
		assert.Equal(t, http.StatusOK, w.Code, "expected 200 for %s", tc.path)
		assert.True(t, *tc.hit, "handler not reached for %s", tc.path)
	}
}

// formatGoldenRouteTable renders entries as the Go source for goldenRouteTable, used
// to regenerate the golden fixture. It is not a test: it is invoked from
// TestRouteTableParity when CFGMS_REGEN_GOLDEN_ROUTES is set, so the fixture can be
// regenerated deterministically alongside the assertion that consumes it.
func formatGoldenRouteTable(entries []routeEntry) string {
	var sb strings.Builder
	sb.WriteString("var goldenRouteTable = []string{\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "\t%q,\n", e.String())
	}
	sb.WriteString("}\n")
	return sb.String()
}
