// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: controller/config.proto

package controller

import (
	common "github.com/cfgis/cfgms/api/proto/common"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationError_Level int32

const (
	ValidationError_INFO     ValidationError_Level = 0
	ValidationError_WARNING  ValidationError_Level = 1
	ValidationError_ERROR    ValidationError_Level = 2
	ValidationError_CRITICAL ValidationError_Level = 3
)

// Enum value maps for ValidationError_Level.
var (
	ValidationError_Level_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "ERROR",
		3: "CRITICAL",
	}
	ValidationError_Level_value = map[string]int32{
		"INFO":     0,
		"WARNING":  1,
		"ERROR":    2,
		"CRITICAL": 3,
	}
)

func (x ValidationError_Level) Enum() *ValidationError_Level {
	p := new(ValidationError_Level)
	*p = x
	return p
}

func (x ValidationError_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationError_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_config_proto_enumTypes[0].Descriptor()
}

func (ValidationError_Level) Type() protoreflect.EnumType {
	return &file_controller_config_proto_enumTypes[0]
}

func (x ValidationError_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationError_Level.Descriptor instead.
func (ValidationError_Level) EnumDescriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{6, 0}
}

type ConfigurationUpdate_UpdateType int32

const (
	ConfigurationUpdate_UNKNOWN ConfigurationUpdate_UpdateType = 0
	ConfigurationUpdate_INITIAL ConfigurationUpdate_UpdateType = 1
	ConfigurationUpdate_UPDATE  ConfigurationUpdate_UpdateType = 2
	ConfigurationUpdate_DELETE  ConfigurationUpdate_UpdateType = 3
)

// Enum value maps for ConfigurationUpdate_UpdateType.
var (
	ConfigurationUpdate_UpdateType_name = map[int32]string{
		0: "UNKNOWN",
		1: "INITIAL",
		2: "UPDATE",
		3: "DELETE",
	}
	ConfigurationUpdate_UpdateType_value = map[string]int32{
		"UNKNOWN": 0,
		"INITIAL": 1,
		"UPDATE":  2,
		"DELETE":  3,
	}
)

func (x ConfigurationUpdate_UpdateType) Enum() *ConfigurationUpdate_UpdateType {
	p := new(ConfigurationUpdate_UpdateType)
	*p = x
	return p
}

func (x ConfigurationUpdate_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigurationUpdate_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_config_proto_enumTypes[1].Descriptor()
}

func (ConfigurationUpdate_UpdateType) Type() protoreflect.EnumType {
	return &file_controller_config_proto_enumTypes[1]
}

func (x ConfigurationUpdate_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigurationUpdate_UpdateType.Descriptor instead.
func (ConfigurationUpdate_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{8, 0}
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Modules       []string               `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_controller_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigRequest) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *ConfigRequest) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Config        *SignedConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // Protobuf configuration with embedded signature
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_controller_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ConfigResponse) GetConfig() *SignedConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ConfigStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Status        *common.Status         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Modules       []*ModuleStatus        `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigStatusReport) Reset() {
	*x = ConfigStatusReport{}
	mi := &file_controller_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigStatusReport) ProtoMessage() {}

func (x *ConfigStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigStatusReport.ProtoReflect.Descriptor instead.
func (*ConfigStatusReport) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigStatusReport) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *ConfigStatusReport) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConfigStatusReport) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ConfigStatusReport) GetModules() []*ModuleStatus {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ModuleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        *common.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleStatus) Reset() {
	*x = ModuleStatus{}
	mi := &file_controller_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatus) ProtoMessage() {}

func (x *ModuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatus.ProtoReflect.Descriptor instead.
func (*ModuleStatus) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleStatus) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ModuleStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ModuleStatus) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ConfigValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"` // JSON encoded configuration
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValidationRequest) Reset() {
	*x = ConfigValidationRequest{}
	mi := &file_controller_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValidationRequest) ProtoMessage() {}

func (x *ConfigValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValidationRequest.ProtoReflect.Descriptor instead.
func (*ConfigValidationRequest) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigValidationRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigValidationRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ConfigValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValidationResponse) Reset() {
	*x = ConfigValidationResponse{}
	mi := &file_controller_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValidationResponse) ProtoMessage() {}

func (x *ConfigValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValidationResponse.ProtoReflect.Descriptor instead.
func (*ConfigValidationResponse) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigValidationResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ConfigValidationResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ConfigValidationResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Level         ValidationError_Level  `protobuf:"varint,3,opt,name=level,proto3,enum=cfgms.api.controller.ValidationError_Level" json:"level,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Suggestion    string                 `protobuf:"bytes,5,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_controller_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{6}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetLevel() ValidationError_Level {
	if x != nil {
		return x.Level
	}
	return ValidationError_INFO
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidationError) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type ConfigStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Modules       []string               `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigStreamRequest) Reset() {
	*x = ConfigStreamRequest{}
	mi := &file_controller_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigStreamRequest) ProtoMessage() {}

func (x *ConfigStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigStreamRequest.ProtoReflect.Descriptor instead.
func (*ConfigStreamRequest) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigStreamRequest) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *ConfigStreamRequest) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ConfigurationUpdate struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	StewardId     string                         `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Config        []byte                         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // JSON encoded configuration
	Version       string                         `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamp.Timestamp           `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UpdateType    ConfigurationUpdate_UpdateType `protobuf:"varint,5,opt,name=update_type,json=updateType,proto3,enum=cfgms.api.controller.ConfigurationUpdate_UpdateType" json:"update_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationUpdate) Reset() {
	*x = ConfigurationUpdate{}
	mi := &file_controller_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdate) ProtoMessage() {}

func (x *ConfigurationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdate.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdate) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigurationUpdate) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *ConfigurationUpdate) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigurationUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigurationUpdate) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ConfigurationUpdate) GetUpdateType() ConfigurationUpdate_UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return ConfigurationUpdate_UNKNOWN
}

// StewardConfig represents the complete steward configuration
type StewardConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steward       *StewardSettings       `protobuf:"bytes,1,opt,name=steward,proto3" json:"steward,omitempty"`
	Resources     []*ResourceConfig      `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Modules       map[string]string      `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StewardConfig) Reset() {
	*x = StewardConfig{}
	mi := &file_controller_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StewardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StewardConfig) ProtoMessage() {}

func (x *StewardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StewardConfig.ProtoReflect.Descriptor instead.
func (*StewardConfig) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{9}
}

func (x *StewardConfig) GetSteward() *StewardSettings {
	if x != nil {
		return x.Steward
	}
	return nil
}

func (x *StewardConfig) GetResources() []*ResourceConfig {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *StewardConfig) GetModules() map[string]string {
	if x != nil {
		return x.Modules
	}
	return nil
}

// StewardSettings contains steward-specific configuration
type StewardSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	ModulePaths   []string               `protobuf:"bytes,3,rep,name=module_paths,json=modulePaths,proto3" json:"module_paths,omitempty"`
	Logging       *LoggingConfig         `protobuf:"bytes,4,opt,name=logging,proto3" json:"logging,omitempty"`
	ErrorHandling *ErrorHandlingConfig   `protobuf:"bytes,5,opt,name=error_handling,json=errorHandling,proto3" json:"error_handling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StewardSettings) Reset() {
	*x = StewardSettings{}
	mi := &file_controller_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StewardSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StewardSettings) ProtoMessage() {}

func (x *StewardSettings) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StewardSettings.ProtoReflect.Descriptor instead.
func (*StewardSettings) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{10}
}

func (x *StewardSettings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StewardSettings) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StewardSettings) GetModulePaths() []string {
	if x != nil {
		return x.ModulePaths
	}
	return nil
}

func (x *StewardSettings) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *StewardSettings) GetErrorHandling() *ErrorHandlingConfig {
	if x != nil {
		return x.ErrorHandling
	}
	return nil
}

// LoggingConfig defines logging output settings
type LoggingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingConfig) Reset() {
	*x = LoggingConfig{}
	mi := &file_controller_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingConfig) ProtoMessage() {}

func (x *LoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingConfig.ProtoReflect.Descriptor instead.
func (*LoggingConfig) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{11}
}

func (x *LoggingConfig) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LoggingConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// ErrorHandlingConfig defines error handling strategies
type ErrorHandlingConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ModuleLoadFailure  string                 `protobuf:"bytes,1,opt,name=module_load_failure,json=moduleLoadFailure,proto3" json:"module_load_failure,omitempty"`
	ResourceFailure    string                 `protobuf:"bytes,2,opt,name=resource_failure,json=resourceFailure,proto3" json:"resource_failure,omitempty"`
	ConfigurationError string                 `protobuf:"bytes,3,opt,name=configuration_error,json=configurationError,proto3" json:"configuration_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ErrorHandlingConfig) Reset() {
	*x = ErrorHandlingConfig{}
	mi := &file_controller_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorHandlingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorHandlingConfig) ProtoMessage() {}

func (x *ErrorHandlingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorHandlingConfig.ProtoReflect.Descriptor instead.
func (*ErrorHandlingConfig) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorHandlingConfig) GetModuleLoadFailure() string {
	if x != nil {
		return x.ModuleLoadFailure
	}
	return ""
}

func (x *ErrorHandlingConfig) GetResourceFailure() string {
	if x != nil {
		return x.ResourceFailure
	}
	return ""
}

func (x *ErrorHandlingConfig) GetConfigurationError() string {
	if x != nil {
		return x.ConfigurationError
	}
	return ""
}

// ResourceConfig defines a single resource to be managed
type ResourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Config        *_struct.Struct        `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"` // Dynamic configuration map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceConfig) Reset() {
	*x = ResourceConfig{}
	mi := &file_controller_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig) ProtoMessage() {}

func (x *ResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig.ProtoReflect.Descriptor instead.
func (*ResourceConfig) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceConfig) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ResourceConfig) GetConfig() *_struct.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// ConfigSignature contains cryptographic signature information
type ConfigSignature struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Algorithm      string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Signature      string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	KeyFingerprint string                 `protobuf:"bytes,4,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigSignature) Reset() {
	*x = ConfigSignature{}
	mi := &file_controller_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSignature) ProtoMessage() {}

func (x *ConfigSignature) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSignature.ProtoReflect.Descriptor instead.
func (*ConfigSignature) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigSignature) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ConfigSignature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ConfigSignature) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConfigSignature) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

// SignedConfig wraps configuration with embedded signature
type SignedConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *StewardConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Signature     *ConfigSignature       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedConfig) Reset() {
	*x = SignedConfig{}
	mi := &file_controller_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedConfig) ProtoMessage() {}

func (x *SignedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controller_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedConfig.ProtoReflect.Descriptor instead.
func (*SignedConfig) Descriptor() ([]byte, []int) {
	return file_controller_config_proto_rawDescGZIP(), []int{15}
}

func (x *SignedConfig) GetConfig() *StewardConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SignedConfig) GetSignature() *ConfigSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_controller_config_proto protoreflect.FileDescriptor

const file_controller_config_proto_rawDesc = "" +
	"\n" +
	"\x17controller/config.proto\x12\x14cfgms.api.controller\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"H\n" +
	"\rConfigRequest\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12\x18\n" +
	"\amodules\x18\x02 \x03(\tR\amodules\"\x98\x01\n" +
	"\x0eConfigResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.cfgms.api.common.StatusR\x06status\x12:\n" +
	"\x06config\x18\x02 \x01(\v2\".cfgms.api.controller.SignedConfigR\x06config\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xca\x01\n" +
	"\x12ConfigStatusReport\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x18.cfgms.api.common.StatusR\x06status\x12<\n" +
	"\amodules\x18\x04 \x03(\v2\".cfgms.api.controller.ModuleStatusR\amodules\"\xa8\x01\n" +
	"\fModuleStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x06status\x18\x02 \x01(\v2\x18.cfgms.api.common.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"K\n" +
	"\x17ConfigValidationRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xa2\x02\n" +
	"\x18ConfigValidationResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.cfgms.api.common.StatusR\x06status\x12=\n" +
	"\x06errors\x18\x02 \x03(\v2%.cfgms.api.controller.ValidationErrorR\x06errors\x12X\n" +
	"\bmetadata\x18\x03 \x03(\v2<.cfgms.api.controller.ConfigValidationResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x05level\x18\x03 \x01(\x0e2+.cfgms.api.controller.ValidationError.LevelR\x05level\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x05 \x01(\tR\n" +
	"suggestion\"7\n" +
	"\x05Level\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03\"N\n" +
	"\x13ConfigStreamRequest\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12\x18\n" +
	"\amodules\x18\x02 \x03(\tR\amodules\"\xb7\x02\n" +
	"\x13ConfigurationUpdate\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12U\n" +
	"\vupdate_type\x18\x05 \x01(\x0e24.cfgms.api.controller.ConfigurationUpdate.UpdateTypeR\n" +
	"updateType\">\n" +
	"\n" +
	"UpdateType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aINITIAL\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\"\x9c\x02\n" +
	"\rStewardConfig\x12?\n" +
	"\asteward\x18\x01 \x01(\v2%.cfgms.api.controller.StewardSettingsR\asteward\x12B\n" +
	"\tresources\x18\x02 \x03(\v2$.cfgms.api.controller.ResourceConfigR\tresources\x12J\n" +
	"\amodules\x18\x03 \x03(\v20.cfgms.api.controller.StewardConfig.ModulesEntryR\amodules\x1a:\n" +
	"\fModulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x01\n" +
	"\x0fStewardSettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12!\n" +
	"\fmodule_paths\x18\x03 \x03(\tR\vmodulePaths\x12=\n" +
	"\alogging\x18\x04 \x01(\v2#.cfgms.api.controller.LoggingConfigR\alogging\x12P\n" +
	"\x0eerror_handling\x18\x05 \x01(\v2).cfgms.api.controller.ErrorHandlingConfigR\rerrorHandling\"=\n" +
	"\rLoggingConfig\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\xa1\x01\n" +
	"\x13ErrorHandlingConfig\x12.\n" +
	"\x13module_load_failure\x18\x01 \x01(\tR\x11moduleLoadFailure\x12)\n" +
	"\x10resource_failure\x18\x02 \x01(\tR\x0fresourceFailure\x12/\n" +
	"\x13configuration_error\x18\x03 \x01(\tR\x12configurationError\"m\n" +
	"\x0eResourceConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"\x94\x01\n" +
	"\x0fConfigSignature\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fkey_fingerprint\x18\x04 \x01(\tR\x0ekeyFingerprint\"\x90\x01\n" +
	"\fSignedConfig\x12;\n" +
	"\x06config\x18\x01 \x01(\v2#.cfgms.api.controller.StewardConfigR\x06config\x12C\n" +
	"\tsignature\x18\x02 \x01(\v2%.cfgms.api.controller.ConfigSignatureR\tsignatureB-Z+github.com/cfgis/cfgms/api/proto/controllerb\x06proto3"

var (
	file_controller_config_proto_rawDescOnce sync.Once
	file_controller_config_proto_rawDescData []byte
)

func file_controller_config_proto_rawDescGZIP() []byte {
	file_controller_config_proto_rawDescOnce.Do(func() {
		file_controller_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_config_proto_rawDesc), len(file_controller_config_proto_rawDesc)))
	})
	return file_controller_config_proto_rawDescData
}

var file_controller_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_controller_config_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_controller_config_proto_goTypes = []any{
	(ValidationError_Level)(0),          // 0: cfgms.api.controller.ValidationError.Level
	(ConfigurationUpdate_UpdateType)(0), // 1: cfgms.api.controller.ConfigurationUpdate.UpdateType
	(*ConfigRequest)(nil),               // 2: cfgms.api.controller.ConfigRequest
	(*ConfigResponse)(nil),              // 3: cfgms.api.controller.ConfigResponse
	(*ConfigStatusReport)(nil),          // 4: cfgms.api.controller.ConfigStatusReport
	(*ModuleStatus)(nil),                // 5: cfgms.api.controller.ModuleStatus
	(*ConfigValidationRequest)(nil),     // 6: cfgms.api.controller.ConfigValidationRequest
	(*ConfigValidationResponse)(nil),    // 7: cfgms.api.controller.ConfigValidationResponse
	(*ValidationError)(nil),             // 8: cfgms.api.controller.ValidationError
	(*ConfigStreamRequest)(nil),         // 9: cfgms.api.controller.ConfigStreamRequest
	(*ConfigurationUpdate)(nil),         // 10: cfgms.api.controller.ConfigurationUpdate
	(*StewardConfig)(nil),               // 11: cfgms.api.controller.StewardConfig
	(*StewardSettings)(nil),             // 12: cfgms.api.controller.StewardSettings
	(*LoggingConfig)(nil),               // 13: cfgms.api.controller.LoggingConfig
	(*ErrorHandlingConfig)(nil),         // 14: cfgms.api.controller.ErrorHandlingConfig
	(*ResourceConfig)(nil),              // 15: cfgms.api.controller.ResourceConfig
	(*ConfigSignature)(nil),             // 16: cfgms.api.controller.ConfigSignature
	(*SignedConfig)(nil),                // 17: cfgms.api.controller.SignedConfig
	nil,                                 // 18: cfgms.api.controller.ConfigValidationResponse.MetadataEntry
	nil,                                 // 19: cfgms.api.controller.StewardConfig.ModulesEntry
	(*common.Status)(nil),               // 20: cfgms.api.common.Status
	(*timestamp.Timestamp)(nil),         // 21: google.protobuf.Timestamp
	(*_struct.Struct)(nil),              // 22: google.protobuf.Struct
}
var file_controller_config_proto_depIdxs = []int32{
	20, // 0: cfgms.api.controller.ConfigResponse.status:type_name -> cfgms.api.common.Status
	17, // 1: cfgms.api.controller.ConfigResponse.config:type_name -> cfgms.api.controller.SignedConfig
	20, // 2: cfgms.api.controller.ConfigStatusReport.status:type_name -> cfgms.api.common.Status
	5,  // 3: cfgms.api.controller.ConfigStatusReport.modules:type_name -> cfgms.api.controller.ModuleStatus
	20, // 4: cfgms.api.controller.ModuleStatus.status:type_name -> cfgms.api.common.Status
	21, // 5: cfgms.api.controller.ModuleStatus.timestamp:type_name -> google.protobuf.Timestamp
	20, // 6: cfgms.api.controller.ConfigValidationResponse.status:type_name -> cfgms.api.common.Status
	8,  // 7: cfgms.api.controller.ConfigValidationResponse.errors:type_name -> cfgms.api.controller.ValidationError
	18, // 8: cfgms.api.controller.ConfigValidationResponse.metadata:type_name -> cfgms.api.controller.ConfigValidationResponse.MetadataEntry
	0,  // 9: cfgms.api.controller.ValidationError.level:type_name -> cfgms.api.controller.ValidationError.Level
	21, // 10: cfgms.api.controller.ConfigurationUpdate.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 11: cfgms.api.controller.ConfigurationUpdate.update_type:type_name -> cfgms.api.controller.ConfigurationUpdate.UpdateType
	12, // 12: cfgms.api.controller.StewardConfig.steward:type_name -> cfgms.api.controller.StewardSettings
	15, // 13: cfgms.api.controller.StewardConfig.resources:type_name -> cfgms.api.controller.ResourceConfig
	19, // 14: cfgms.api.controller.StewardConfig.modules:type_name -> cfgms.api.controller.StewardConfig.ModulesEntry
	13, // 15: cfgms.api.controller.StewardSettings.logging:type_name -> cfgms.api.controller.LoggingConfig
	14, // 16: cfgms.api.controller.StewardSettings.error_handling:type_name -> cfgms.api.controller.ErrorHandlingConfig
	22, // 17: cfgms.api.controller.ResourceConfig.config:type_name -> google.protobuf.Struct
	11, // 18: cfgms.api.controller.SignedConfig.config:type_name -> cfgms.api.controller.StewardConfig
	16, // 19: cfgms.api.controller.SignedConfig.signature:type_name -> cfgms.api.controller.ConfigSignature
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_controller_config_proto_init() }
func file_controller_config_proto_init() {
	if File_controller_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_config_proto_rawDesc), len(file_controller_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controller_config_proto_goTypes,
		DependencyIndexes: file_controller_config_proto_depIdxs,
		EnumInfos:         file_controller_config_proto_enumTypes,
		MessageInfos:      file_controller_config_proto_msgTypes,
	}.Build()
	File_controller_config_proto = out.File
	file_controller_config_proto_goTypes = nil
	file_controller_config_proto_depIdxs = nil
}
