// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: controller/controller.proto

package controller

import (
	common "github.com/cfgis/cfgms/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Version     string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	InitialDna  *common.DNA            `protobuf:"bytes,2,opt,name=initial_dna,json=initialDna,proto3" json:"initial_dna,omitempty"`
	Credentials *common.Credentials    `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// Sync verification for reconnections
	LastKnownSync           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_known_sync,json=lastKnownSync,proto3" json:"last_known_sync,omitempty"`
	ExpectedSyncFingerprint string                 `protobuf:"bytes,5,opt,name=expected_sync_fingerprint,json=expectedSyncFingerprint,proto3" json:"expected_sync_fingerprint,omitempty"`
	IsReconnection          bool                   `protobuf:"varint,6,opt,name=is_reconnection,json=isReconnection,proto3" json:"is_reconnection,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_controller_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetInitialDna() *common.DNA {
	if x != nil {
		return x.InitialDna
	}
	return nil
}

func (x *RegisterRequest) GetCredentials() *common.Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *RegisterRequest) GetLastKnownSync() *timestamppb.Timestamp {
	if x != nil {
		return x.LastKnownSync
	}
	return nil
}

func (x *RegisterRequest) GetExpectedSyncFingerprint() string {
	if x != nil {
		return x.ExpectedSyncFingerprint
	}
	return ""
}

func (x *RegisterRequest) GetIsReconnection() bool {
	if x != nil {
		return x.IsReconnection
	}
	return false
}

type RegisterResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StewardId string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Status    *common.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Token     *common.Token          `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Sync verification response
	SyncStatus           *common.SyncStatus `protobuf:"bytes,4,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	RequiresDnaResync    bool               `protobuf:"varint,5,opt,name=requires_dna_resync,json=requiresDnaResync,proto3" json:"requires_dna_resync,omitempty"`
	RequiresConfigResync bool               `protobuf:"varint,6,opt,name=requires_config_resync,json=requiresConfigResync,proto3" json:"requires_config_resync,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_controller_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *RegisterResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RegisterResponse) GetToken() *common.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RegisterResponse) GetSyncStatus() *common.SyncStatus {
	if x != nil {
		return x.SyncStatus
	}
	return nil
}

func (x *RegisterResponse) GetRequiresDnaResync() bool {
	if x != nil {
		return x.RequiresDnaResync
	}
	return false
}

func (x *RegisterResponse) GetRequiresConfigResync() bool {
	if x != nil {
		return x.RequiresConfigResync
	}
	return false
}

type HeartbeatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StewardId string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Status    string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Metrics   map[string]string      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// dna_aggregate_root is the Merkle-style root of the DNA fragment manifest
	// (SHA-256 over sorted (fragment_id, fragment_hash) pairs, ADR-017 §6).
	// Replaces the legacy sync_fingerprint for heartbeat-based DNA currency
	// checks; the controller compares this to its stored root and triggers a
	// partial-sync diff only on mismatch (ADR-017 §7).
	DnaAggregateRoot string `protobuf:"bytes,4,opt,name=dna_aggregate_root,json=dnaAggregateRoot,proto3" json:"dna_aggregate_root,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_controller_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatRequest) GetDnaAggregateRoot() string {
	if x != nil {
		return x.DnaAggregateRoot
	}
	return ""
}

type StewardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StewardRequest) Reset() {
	*x = StewardRequest{}
	mi := &file_controller_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StewardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StewardRequest) ProtoMessage() {}

func (x *StewardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StewardRequest.ProtoReflect.Descriptor instead.
func (*StewardRequest) Descriptor() ([]byte, []int) {
	return file_controller_controller_proto_rawDescGZIP(), []int{3}
}

func (x *StewardRequest) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

var File_controller_controller_proto protoreflect.FileDescriptor

const file_controller_controller_proto_rawDesc = "" +
	"\n" +
	"\x1bcontroller/controller.proto\x12\x14cfgms.api.controller\x1a\x13common/common.proto\x1a\x11common/auth.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x02\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x126\n" +
	"\vinitial_dna\x18\x02 \x01(\v2\x15.cfgms.api.common.DNAR\n" +
	"initialDna\x12?\n" +
	"\vcredentials\x18\x03 \x01(\v2\x1d.cfgms.api.common.CredentialsR\vcredentials\x12B\n" +
	"\x0flast_known_sync\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastKnownSync\x12:\n" +
	"\x19expected_sync_fingerprint\x18\x05 \x01(\tR\x17expectedSyncFingerprint\x12'\n" +
	"\x0fis_reconnection\x18\x06 \x01(\bR\x0eisReconnection\"\xb7\x02\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x120\n" +
	"\x06status\x18\x02 \x01(\v2\x18.cfgms.api.common.StatusR\x06status\x12-\n" +
	"\x05token\x18\x03 \x01(\v2\x17.cfgms.api.common.TokenR\x05token\x12=\n" +
	"\vsync_status\x18\x04 \x01(\v2\x1c.cfgms.api.common.SyncStatusR\n" +
	"syncStatus\x12.\n" +
	"\x13requires_dna_resync\x18\x05 \x01(\bR\x11requiresDnaResync\x124\n" +
	"\x16requires_config_resync\x18\x06 \x01(\bR\x14requiresConfigResync\"\x82\x02\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12M\n" +
	"\ametrics\x18\x03 \x03(\v23.cfgms.api.controller.HeartbeatRequest.MetricsEntryR\ametrics\x12,\n" +
	"\x12dna_aggregate_root\x18\x04 \x01(\tR\x10dnaAggregateRoot\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x0eStewardRequest\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardIdB-Z+github.com/cfgis/cfgms/api/proto/controllerb\x06proto3"

var (
	file_controller_controller_proto_rawDescOnce sync.Once
	file_controller_controller_proto_rawDescData []byte
)

func file_controller_controller_proto_rawDescGZIP() []byte {
	file_controller_controller_proto_rawDescOnce.Do(func() {
		file_controller_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_controller_proto_rawDesc), len(file_controller_controller_proto_rawDesc)))
	})
	return file_controller_controller_proto_rawDescData
}

var file_controller_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_controller_controller_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: cfgms.api.controller.RegisterRequest
	(*RegisterResponse)(nil),      // 1: cfgms.api.controller.RegisterResponse
	(*HeartbeatRequest)(nil),      // 2: cfgms.api.controller.HeartbeatRequest
	(*StewardRequest)(nil),        // 3: cfgms.api.controller.StewardRequest
	nil,                           // 4: cfgms.api.controller.HeartbeatRequest.MetricsEntry
	(*common.DNA)(nil),            // 5: cfgms.api.common.DNA
	(*common.Credentials)(nil),    // 6: cfgms.api.common.Credentials
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*common.Status)(nil),         // 8: cfgms.api.common.Status
	(*common.Token)(nil),          // 9: cfgms.api.common.Token
	(*common.SyncStatus)(nil),     // 10: cfgms.api.common.SyncStatus
}
var file_controller_controller_proto_depIdxs = []int32{
	5,  // 0: cfgms.api.controller.RegisterRequest.initial_dna:type_name -> cfgms.api.common.DNA
	6,  // 1: cfgms.api.controller.RegisterRequest.credentials:type_name -> cfgms.api.common.Credentials
	7,  // 2: cfgms.api.controller.RegisterRequest.last_known_sync:type_name -> google.protobuf.Timestamp
	8,  // 3: cfgms.api.controller.RegisterResponse.status:type_name -> cfgms.api.common.Status
	9,  // 4: cfgms.api.controller.RegisterResponse.token:type_name -> cfgms.api.common.Token
	10, // 5: cfgms.api.controller.RegisterResponse.sync_status:type_name -> cfgms.api.common.SyncStatus
	4,  // 6: cfgms.api.controller.HeartbeatRequest.metrics:type_name -> cfgms.api.controller.HeartbeatRequest.MetricsEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_controller_controller_proto_init() }
func file_controller_controller_proto_init() {
	if File_controller_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_controller_proto_rawDesc), len(file_controller_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controller_controller_proto_goTypes,
		DependencyIndexes: file_controller_controller_proto_depIdxs,
		MessageInfos:      file_controller_controller_proto_msgTypes,
	}.Build()
	File_controller_controller_proto = out.File
	file_controller_controller_proto_goTypes = nil
	file_controller_controller_proto_depIdxs = nil
}
