// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: controller/controller.proto

package controller

import (
	context "context"
	common "github.com/cfgis/cfgms/api/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Controller_Authenticate_FullMethodName       = "/cfgms.api.controller.Controller/Authenticate"
	Controller_AcceptRegistration_FullMethodName = "/cfgms.api.controller.Controller/AcceptRegistration"
	Controller_ProcessHeartbeat_FullMethodName   = "/cfgms.api.controller.Controller/ProcessHeartbeat"
	Controller_SyncDNA_FullMethodName            = "/cfgms.api.controller.Controller/SyncDNA"
	Controller_GetStewardDNA_FullMethodName      = "/cfgms.api.controller.Controller/GetStewardDNA"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	// Authentication
	Authenticate(ctx context.Context, in *common.Credentials, opts ...grpc.CallOption) (*common.Token, error)
	// Steward management
	AcceptRegistration(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	ProcessHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*common.Status, error)
	// DNA management
	SyncDNA(ctx context.Context, in *common.DNA, opts ...grpc.CallOption) (*common.Status, error)
	GetStewardDNA(ctx context.Context, in *StewardRequest, opts ...grpc.CallOption) (*common.DNA, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Authenticate(ctx context.Context, in *common.Credentials, opts ...grpc.CallOption) (*common.Token, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Token)
	err := c.cc.Invoke(ctx, Controller_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) AcceptRegistration(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Controller_AcceptRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ProcessHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*common.Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Status)
	err := c.cc.Invoke(ctx, Controller_ProcessHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SyncDNA(ctx context.Context, in *common.DNA, opts ...grpc.CallOption) (*common.Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Status)
	err := c.cc.Invoke(ctx, Controller_SyncDNA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetStewardDNA(ctx context.Context, in *StewardRequest, opts ...grpc.CallOption) (*common.DNA, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.DNA)
	err := c.cc.Invoke(ctx, Controller_GetStewardDNA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility.
type ControllerServer interface {
	// Authentication
	Authenticate(context.Context, *common.Credentials) (*common.Token, error)
	// Steward management
	AcceptRegistration(context.Context, *RegisterRequest) (*RegisterResponse, error)
	ProcessHeartbeat(context.Context, *HeartbeatRequest) (*common.Status, error)
	// DNA management
	SyncDNA(context.Context, *common.DNA) (*common.Status, error)
	GetStewardDNA(context.Context, *StewardRequest) (*common.DNA, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServer struct{}

func (UnimplementedControllerServer) Authenticate(context.Context, *common.Credentials) (*common.Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedControllerServer) AcceptRegistration(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptRegistration not implemented")
}
func (UnimplementedControllerServer) ProcessHeartbeat(context.Context, *HeartbeatRequest) (*common.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessHeartbeat not implemented")
}
func (UnimplementedControllerServer) SyncDNA(context.Context, *common.DNA) (*common.Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDNA not implemented")
}
func (UnimplementedControllerServer) GetStewardDNA(context.Context, *StewardRequest) (*common.DNA, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStewardDNA not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}
func (UnimplementedControllerServer) testEmbeddedByValue()                    {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	// If the following call pancis, it indicates UnimplementedControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Authenticate(ctx, req.(*common.Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_AcceptRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).AcceptRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_AcceptRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).AcceptRegistration(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ProcessHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ProcessHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ProcessHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ProcessHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SyncDNA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.DNA)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SyncDNA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_SyncDNA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SyncDNA(ctx, req.(*common.DNA))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetStewardDNA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetStewardDNA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_GetStewardDNA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetStewardDNA(ctx, req.(*StewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cfgms.api.controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Controller_Authenticate_Handler,
		},
		{
			MethodName: "AcceptRegistration",
			Handler:    _Controller_AcceptRegistration_Handler,
		},
		{
			MethodName: "ProcessHeartbeat",
			Handler:    _Controller_ProcessHeartbeat_Handler,
		},
		{
			MethodName: "SyncDNA",
			Handler:    _Controller_SyncDNA_Handler,
		},
		{
			MethodName: "GetStewardDNA",
			Handler:    _Controller_GetStewardDNA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller/controller.proto",
}
