// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors
// This file defines supplementary Go types for the common proto package that
// correspond to proto messages declared in common.proto (DriftDiffRecord,
// DriftDiffField) but are not generated by protoc because the generator is not
// available in all build environments. These types are JSON-serializable and are
// used as the wire-transport format for DNA.drift_diffs (field 12, ADR-022 §6):
// records travel as JSON inside DNATransfer.DriftDiffBytes, and DNA.DriftDiffs is
// the controller-side in-memory carrier from reassembleDNA to the entity-graph write.
//
// Deleting this file is part of the next `make proto` run: protoc will generate
// DriftDiffRecord and DriftDiffField into common.pb.go from the declarations already
// present in common.proto, and leaving these hand-written types in place would be a
// duplicate declaration in the same package. The generated shape is source-compatible
// for every field this code reads except that desired/actual become
// *structpb.Value — the proto declares google.protobuf.Value for them, matching the
// interface{} used here, because module state values are arbitrary JSON.
package common

import "time"

// DriftDiffRecord is a managed-resource drift-diff record accumulated by the
// steward convergence loop and shipped in DNA.drift_diffs (ADR-022 §6).
// One record is produced per managed resource per convergence cycle where drift
// was detected.
type DriftDiffRecord struct {
	// FragmentID is the module-internal resource identifier, e.g. "vm:m2-test-vm"
	// or "service:sshd". It is the fragID passed to ResolveSubjectEID on the
	// controller side to construct the entity-graph EID.
	FragmentID string `json:"fragment_id"`

	// Fields is the full compared field set: every managed field including matching
	// ones, not just deltas.
	Fields []*DriftDiffField `json:"fields"`

	// ConfigRevision is the config version applied on the steward at the time of
	// drift detection.
	ConfigRevision string `json:"config_revision"`

	// DetectedAt is when drift was detected on the steward.
	DetectedAt time.Time `json:"detected_at"`
}

// DriftDiffField is one attribute in a DriftDiffRecord comparison.
type DriftDiffField struct {
	// Attribute is the field name.
	Attribute string `json:"attribute"`

	// Desired is the desired value for this field (nil when the field is absent
	// from the desired config but present in the actual state).
	Desired interface{} `json:"desired"`

	// Actual is the actual value for this field (nil when the field is absent
	// from the actual state but present in the desired config).
	Actual interface{} `json:"actual"`

	// Matching is true when Desired == Actual.
	Matching bool `json:"matching"`
}
