// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Jordan Ritz

package main

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/cfgis/cfgms/cmd/steward/service"
	"github.com/cfgis/cfgms/pkg/logging"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// isElevated returns true if the test process has elevated privileges,
// using the platform-specific check from the service package.
func isElevated() bool {
	return service.New("").IsElevated()
}

func TestBuildRootCommand(t *testing.T) {
	cmd := buildRootCommand()
	require.NotNil(t, cmd)
	assert.Equal(t, "cfgms-steward", cmd.Use)

	// Verify subcommands are registered.
	names := make([]string, 0, len(cmd.Commands()))
	for _, sub := range cmd.Commands() {
		names = append(names, sub.Name())
	}
	assert.Contains(t, names, "install")
	assert.Contains(t, names, "uninstall")
	assert.Contains(t, names, "status")
}

func TestBuildRootCommandFlags(t *testing.T) {
	cmd := buildRootCommand()

	for _, name := range []string{"config", "regtoken"} {
		flag := cmd.Flags().Lookup(name)
		assert.NotNil(t, flag, "expected flag %q to be registered", name)
	}

	// log-level and log-provider must not be registered as CLI flags.
	assert.Nil(t, cmd.Flags().Lookup("log-level"), "log-level flag must not be registered")
	assert.Nil(t, cmd.Flags().Lookup("log-provider"), "log-provider flag must not be registered")
}

func TestBuildRootCommandNoModeFlag(t *testing.T) {
	cmd := buildRootCommand()
	assert.Nil(t, cmd.Flags().Lookup("mode"), "mode flag must not be registered")
}

func TestInstallCommandEnforcesRequiredRegtoken(t *testing.T) {
	// Verify cobra's MarkFlagRequired("regtoken") rejects the install subcommand
	// when --regtoken is absent. This is the cobra-level guard that supersedes
	// any manual empty-token check in runInstall — runInstall is never reached
	// without a non-empty token value.
	root := buildRootCommand()
	root.SetOut(io.Discard)
	root.SetErr(io.Discard)
	root.SetArgs([]string{"install"})
	err := root.Execute()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "regtoken")
}

func TestRunInstallRequiresElevation(t *testing.T) {
	if isElevated() {
		t.Skip("test requires non-elevated process — running as root")
	}
	err := runInstall("tok_test_abc123", "", "", false, "", false)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "elevated privileges")
}

func TestRunInstallCACertFileNotFound(t *testing.T) {
	// Verify runInstall returns an error that includes the filename when --ca-cert
	// names a path that does not exist.
	missing := filepath.Join(t.TempDir(), "nonexistent-ca.crt")
	err := runInstall("tok_test_abc123", missing, "", false, "", false)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "nonexistent-ca.crt")
}

func TestBuildInstallCommandFlags(t *testing.T) {
	cmd := buildInstallCommand()
	require.NotNil(t, cmd)

	for _, name := range []string{"regtoken", "ca-cert", "fingerprint", "hyperv", "winrm-user", "winrm-pass-stdin"} {
		flag := cmd.Flags().Lookup(name)
		assert.NotNil(t, flag, "expected flag %q to be registered on install subcommand", name)
	}

	// --winrm-pass (plaintext argv) must NOT be registered per F2 constraint.
	assert.Nil(t, cmd.Flags().Lookup("winrm-pass"),
		"--winrm-pass must not be registered: plaintext argv passwords are prohibited")
}

func TestGenerateRandomPassword(t *testing.T) {
	pass, err := generateRandomPassword(32)
	require.NoError(t, err)
	assert.Len(t, pass, 32, "generated password must be exactly 32 characters")

	// All characters must be alphanumeric.
	for _, c := range pass {
		assert.True(t,
			(c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'),
			"generated password must only contain alphanumeric characters, got %q", c)
	}

	// Two consecutive calls must produce different passwords (with overwhelming probability).
	pass2, err := generateRandomPassword(32)
	require.NoError(t, err)
	assert.NotEqual(t, pass, pass2, "consecutive passwords must differ")
}

func TestResolveWinRMPassword_AutoGenerate(t *testing.T) {
	pass, autoGenerated, err := resolveWinRMPassword(false)
	require.NoError(t, err)
	assert.True(t, autoGenerated, "must report auto-generated when fromStdin=false")
	assert.Len(t, pass, 32, "auto-generated password must be 32 characters")
}

// TestAutoGeneratedPasswordNotice_NoPasswordValue is a regression test for the
// CodeQL go/clear-text-logging (CWE-312/532) finding on PR #1860: the operator
// notice printed after an auto-generated password install must not contain the
// password value itself. Operators retrieve the value from the secret store.
func TestAutoGeneratedPasswordNotice_NoPasswordValue(t *testing.T) {
	notice := autoGeneratedPasswordNotice()

	// Notice must mention the secret store key so operators know where to look.
	assert.Contains(t, notice, "hyperv/winrm_pass",
		"notice must name the secret store key so operators can retrieve the password")

	// Notice must not contain a "%s" format verb — if it did, that would be a
	// sign someone is passing the password value into a format call.
	assert.NotContains(t, notice, "%s",
		"notice must be a literal string, never a format string with a password placeholder")

	// Generate a recognisable password value and assert it does not appear in
	// the notice when paired with a typical auto-generate flow.
	pass, autoGenerated, err := resolveWinRMPassword(false)
	require.NoError(t, err)
	require.True(t, autoGenerated)
	require.Len(t, pass, 32)
	assert.NotContains(t, notice, pass,
		"notice must never contain the auto-generated password value")
}

func TestResolveWinRMPassword_Stdin(t *testing.T) {
	// Redirect stdin to a pipe for the test.
	r, w, err := os.Pipe()
	require.NoError(t, err)
	oldStdin := os.Stdin
	os.Stdin = r
	defer func() { os.Stdin = oldStdin }()

	_, writeErr := w.WriteString("secretFromStdin\n")
	require.NoError(t, writeErr)
	require.NoError(t, w.Close())

	pass, autoGenerated, err := resolveWinRMPassword(true)
	require.NoError(t, err)
	assert.False(t, autoGenerated, "must report not auto-generated when fromStdin=true")
	assert.Equal(t, "secretFromStdin", pass)
}

func TestResolveWinRMPassword_StdinEmpty(t *testing.T) {
	// Stdin is empty (immediate EOF) → error.
	r, w, err := os.Pipe()
	require.NoError(t, err)
	require.NoError(t, w.Close()) // close immediately to produce EOF
	oldStdin := os.Stdin
	os.Stdin = r
	defer func() { os.Stdin = oldStdin }()

	_, _, err = resolveWinRMPassword(true)
	require.Error(t, err, "empty stdin must return an error")
	assert.Contains(t, err.Error(), "stdin is empty")
}

func TestResolveWinRMPassword_StdinEmptyLine(t *testing.T) {
	// Stdin contains only a blank line → reject empty password.
	r, w, err := os.Pipe()
	require.NoError(t, err)
	_, writeErr := w.WriteString("\n")
	require.NoError(t, writeErr)
	require.NoError(t, w.Close())
	oldStdin := os.Stdin
	os.Stdin = r
	defer func() { os.Stdin = oldStdin }()

	_, _, err = resolveWinRMPassword(true)
	require.Error(t, err, "blank stdin line must return an error")
	assert.Contains(t, err.Error(), "empty")
}

func TestRunUninstallRequiresElevation(t *testing.T) {
	if isElevated() {
		t.Skip("test requires non-elevated process — running as root")
	}
	err := runUninstall(false)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "elevated privileges")
}

func TestRunStatusNotInstalled(t *testing.T) {
	// status should succeed even when the service is not installed.
	err := runStatus()
	assert.NoError(t, err)
}

func TestBuildHTTPConfig(t *testing.T) {
	logger := logging.NewLogger("debug")

	t.Run("empty CFGMS_HTTP_CA_CERT_PATH produces empty CACertPath", func(t *testing.T) {
		t.Setenv("CFGMS_HTTP_CA_CERT_PATH", "")
		cfg := buildHTTPConfig("https://controller.example.com", 30*time.Second, logger)
		require.NotNil(t, cfg)
		assert.Equal(t, "https://controller.example.com", cfg.ControllerURL)
		// CACertPath is "" when no env var is set and platform-standard cert does not exist.
		// In test environments the platform cert is absent, so this holds.
		assert.Equal(t, "", cfg.CACertPath)
	})

	t.Run("CFGMS_HTTP_CA_CERT_PATH with existing file is forwarded to HTTPConfig.CACertPath", func(t *testing.T) {
		dir := t.TempDir()
		certFile := filepath.Join(dir, "ca.crt")
		require.NoError(t, os.WriteFile(certFile, []byte("fake-cert"), 0600))
		t.Setenv("CFGMS_HTTP_CA_CERT_PATH", certFile)
		cfg := buildHTTPConfig("https://controller.example.com", 30*time.Second, logger)
		require.NotNil(t, cfg)
		assert.Equal(t, certFile, cfg.CACertPath)
	})
}

func TestResolveRegistrationCACertPath(t *testing.T) {
	logger := logging.NewLogger("debug")

	t.Run("priority 1: env var set and file exists", func(t *testing.T) {
		dir := t.TempDir()
		certFile := filepath.Join(dir, "ca.crt")
		require.NoError(t, os.WriteFile(certFile, []byte("fake-cert"), 0600))
		t.Setenv("CFGMS_HTTP_CA_CERT_PATH", certFile)

		result := doResolveRegistrationCACertPath(logger, filepath.Join(dir, "platform-ca.crt"))
		assert.Equal(t, certFile, result)
	})

	t.Run("priority 1 fallthrough: env var set but file missing; platform path used", func(t *testing.T) {
		dir := t.TempDir()
		platformCert := filepath.Join(dir, "platform-ca.crt")
		require.NoError(t, os.WriteFile(platformCert, []byte("fake-cert"), 0600))
		t.Setenv("CFGMS_HTTP_CA_CERT_PATH", filepath.Join(dir, "nonexistent.crt"))

		result := doResolveRegistrationCACertPath(logger, platformCert)
		assert.Equal(t, platformCert, result)
	})

	t.Run("priority 2: platform-standard path exists when env var is empty", func(t *testing.T) {
		dir := t.TempDir()
		platformCert := filepath.Join(dir, "controller-ca.crt")
		require.NoError(t, os.WriteFile(platformCert, []byte("fake-cert"), 0600))
		t.Setenv("CFGMS_HTTP_CA_CERT_PATH", "")

		result := doResolveRegistrationCACertPath(logger, platformCert)
		assert.Equal(t, platformCert, result)
	})

	t.Run("priority 3: neither env var nor platform path exists returns empty string", func(t *testing.T) {
		dir := t.TempDir()
		t.Setenv("CFGMS_HTTP_CA_CERT_PATH", "")

		result := doResolveRegistrationCACertPath(logger, filepath.Join(dir, "nonexistent.crt"))
		assert.Equal(t, "", result)
	})
}

func TestTryReconnectWithStoredIdentity_NoStoredIdentity_FallsThrough(t *testing.T) {
	// No identity file on disk — first run. The function returns (nil, nil) so
	// the caller falls through to HTTP registration without logging an error.
	dir := t.TempDir()
	tc, err := tryReconnectWithStoredIdentity(context.Background(), dir, "token", logging.NewLogger("error"))
	assert.Nil(t, tc)
	assert.NoError(t, err)
}

func TestTryReconnectWithStoredIdentity_MissingServerCert_RejectsAndFallsBack(t *testing.T) {
	// An identity record that lacks both ServerCertPEM and SigningCertPEM cannot
	// verify signed sync_config commands. The reconnect must reject it with an
	// explicit error so the caller falls back to HTTP re-registration rather than
	// reconnecting into a state where every signed command is silently dropped.
	dir := t.TempDir()
	require.NoError(t, saveIdentity(dir, StewardIdentity{
		StewardID:        "steward-no-cert",
		TenantID:         "tenant-1",
		TransportAddress: "controller:4433",
		CACertPEM:        "-----BEGIN CERTIFICATE-----\nca\n-----END CERTIFICATE-----",
	}))

	tc, err := tryReconnectWithStoredIdentity(context.Background(), dir, "token", logging.NewLogger("error"))
	assert.Nil(t, tc)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "missing controller server/signing certificate")
}

func TestTryReconnectWithStoredIdentity_CorruptIdentity_FallsThrough(t *testing.T) {
	// A corrupt identity file is not fatal — loadIdentity returns an error, which
	// the reconnect treats as "no usable identity" and returns (nil, nil) so the
	// caller falls through to HTTP registration.
	dir := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(dir, identityFileName), []byte("{not json"), 0600))

	tc, err := tryReconnectWithStoredIdentity(context.Background(), dir, "token", logging.NewLogger("error"))
	assert.Nil(t, tc)
	assert.NoError(t, err)
}

func TestControllerURLOrUnknown(t *testing.T) {
	// When ControllerURL is empty (default in test builds).
	original := ControllerURL
	defer func() { ControllerURL = original }()

	ControllerURL = ""
	assert.Contains(t, controllerURLOrUnknown(), "not set")

	ControllerURL = "https://ctrl.example.com"
	assert.Equal(t, "https://ctrl.example.com", controllerURLOrUnknown())
}

func TestLogLevelFromEnv(t *testing.T) {
	tests := []struct {
		env      string
		expected string
	}{
		{"", "INFO"},
		{"invalid", "INFO"},
		{"info", "INFO"},
		{"INFO", "INFO"},
		{"debug", "DEBUG"},
		{"DEBUG", "DEBUG"},
		{"warn", "WARN"},
		{"WARN", "WARN"},
		{"error", "ERROR"},
		{"ERROR", "ERROR"},
		{"verbose", "INFO"},
	}

	for _, tc := range tests {
		t.Run("env="+tc.env, func(t *testing.T) {
			t.Setenv("CFGMS_LOG_LEVEL", tc.env)
			assert.Equal(t, tc.expected, logLevelFromEnv())
		})
	}
}

// TestStandaloneStartErrorPropagatesToRunSteward verifies that startup errors in
// standalone mode are returned as errors from runSteward rather than terminating
// the process via logger.Fatal / os.Exit. Uses a non-existent config path to
// trigger a known-bad startup error from steward.NewStandalone.
func TestStandaloneStartErrorPropagatesToRunSteward(t *testing.T) {
	t.Setenv("CFGMS_LOG_DIR", t.TempDir())

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	err := runSteward(ctx, "", "/nonexistent/cfgms-config-does-not-exist.yaml")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "failed to create standalone steward")
}
