// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Jordan Ritz

//go:build integration

package main

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"sync/atomic"
	"testing"
	"time"

	"github.com/cfgis/cfgms/features/steward/registration"
	"github.com/cfgis/cfgms/pkg/logging"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestManualReviewFlow_RegisterPollApprove is the end-to-end integration test for the
// manual-review registration flow (Issue #1899).
//
// Scenario:
//  1. Register → controller returns HTTP 202 (pending manual approval); the real
//     HTTPClient generates a steward keypair and submits its public half as a CSR
//     (Issue #3780)
//  2. Pending ID is persisted to disk so restarts resume the same record
//  3. pollForApproval polls the status endpoint: first call returns "pending",
//     second call returns "claimed" with cert fields (no client_key on the wire)
//  4. approvedRegistration is returned with the full cert data, its ClientKey
//     sourced from the keypair Register generated — never from the wire
//  5. Pending state file is cleared after approval
//
// "Successful connect" here means the approval cycle completes and the steward
// receives the cert bundle required to establish a gRPC transport connection.
// The actual gRPC dial is out of scope for this test (requires a live controller).
func TestManualReviewFlow_RegisterPollApprove(t *testing.T) {
	const pendingID = "pending-manual-abc123"
	logger := logging.NewLogger("error")

	// Simulate certificate fields returned by the controller on approval. No
	// client_key field: the controller never generates or sees a private key for
	// this credential (Issue #3780).
	approvedBody := registration.RegistrationStatusResponse{
		Status:           "claimed",
		StewardID:        "steward-integration-test",
		TenantID:         "tenant-test",
		Group:            "default",
		TransportAddress: "ctrl.example.com:4433",
		ClientCert:       "-----BEGIN CERTIFICATE-----\nCLIENT\n-----END CERTIFICATE-----",
		CACert:           "-----BEGIN CERTIFICATE-----\nCA\n-----END CERTIFICATE-----",
		ServerCert:       "-----BEGIN CERTIFICATE-----\nSERVER\n-----END CERTIFICATE-----",
	}
	approvedJSON, err := json.Marshal(approvedBody)
	require.NoError(t, err)

	var statusCallCount atomic.Int32
	var gotCSRPEM string

	// httptest.Server simulates both the controller's register and status
	// endpoints. POST /api/v1/register returns 202 pending (recording the
	// submitted CSR); GET status first returns "pending", second returns
	// "claimed" with certs.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if r.Method == http.MethodPost && r.URL.Path == "/api/v1/register" {
			var req registration.RegistrationRequest
			require.NoError(t, json.NewDecoder(r.Body).Decode(&req))
			gotCSRPEM = req.CSRPEM
			w.WriteHeader(http.StatusAccepted)
			_, _ = w.Write([]byte(`{"pending_id":"` + pendingID + `","steward_id":"steward-integration-test","tenant_id":"tenant-test","status":"pending"}`))
			return
		}
		w.WriteHeader(http.StatusOK)
		n := statusCallCount.Add(1)
		if n == 1 {
			_, _ = w.Write([]byte(`{"status":"pending"}`))
		} else {
			_, _ = w.Write(approvedJSON)
		}
	}))
	defer srv.Close()

	httpClient, err := registration.NewHTTPClient(&registration.HTTPConfig{
		ControllerURL: srv.URL,
		Logger:        logger,
	})
	require.NoError(t, err)

	certStoreDir := t.TempDir()

	// === Phase 1: Register — controller returns 202, steward submits a CSR ===
	regResp, pendingResp, regErr := httpClient.Register(context.Background(), registration.RegistrationRequest{Token: "reg-token-abc"})
	require.NoError(t, regErr)
	require.Nil(t, regResp, "immediate RegistrationResponse must be nil on 202")
	require.NotNil(t, pendingResp)
	assert.Equal(t, pendingID, pendingResp.PendingID)
	assert.NotEmpty(t, gotCSRPEM, "Register must submit a non-empty CSR")

	// Persist the pending ID (as registerAndConnect would after receiving 202).
	require.NoError(t, savePendingState(certStoreDir, PendingState{PendingID: pendingResp.PendingID}))

	// Verify persistence: a simulated restart can load the same pending ID.
	loaded, err := loadPendingState(certStoreDir)
	require.NoError(t, err)
	require.NotNil(t, loaded)
	assert.Equal(t, pendingID, loaded.PendingID, "persisted pending ID must survive restart")

	// === Phase 2: Poll for approval — pending then claimed, same httpClient so
	// the keypair generated by Register above is available to pair with the
	// claimed certificate. ===
	result, pollErr := pollForApproval(
		context.Background(),
		httpClient,
		pendingResp.PendingID,
		"reg-token-abc",
		30*time.Second,
		0, // skip sleep in test
		0,
		logger,
	)

	require.NoError(t, pollErr)
	require.NotNil(t, result, "approvedRegistration must be non-nil on successful approval")

	// === Phase 3: Assert successful cert receipt (the "successful connect" AC) ===
	assert.Equal(t, "steward-integration-test", result.StewardID)
	assert.Equal(t, "tenant-test", result.TenantID)
	assert.Equal(t, "ctrl.example.com:4433", result.TransportAddress)
	assert.NotEmpty(t, result.ClientCert, "client cert must be populated on approval")
	assert.NotEmpty(t, result.ClientKey, "client key must be populated from the locally generated keypair")
	assert.NotEmpty(t, result.CACert, "CA cert must be populated on approval")

	assert.Equal(t, int32(2), statusCallCount.Load(),
		"must poll exactly twice: once for pending, once for claimed")

	// === Phase 4: Clear pending state after approval ===
	require.NoError(t, clearPendingState(certStoreDir))
	cleared, err := loadPendingState(certStoreDir)
	require.NoError(t, err)
	assert.Nil(t, cleared, "pending state must be cleared after approval")
}

// TestManualReviewFlow_RestartResumesPendingID verifies that a steward restart loads the
// persisted pending_id and resumes polling rather than creating a new pending record —
// and, per the PR #3844 acceptance-review finding, that the resumed process ends up with
// a genuinely usable credential, not just a resumed pending_id. Register runs on a
// separate, "pre-restart" HTTPClient instance; the "restart" is a brand-new HTTPClient
// instance that never called Register and so never generated a keypair of its own —
// exactly the failure condition the finding described. Only persisting the CSR key
// alongside PendingState and restoring it via ResumePendingClientKey before polling
// lets the resumed instance pair the claimed certificate with a usable key.
func TestManualReviewFlow_RestartResumesPendingID(t *testing.T) {
	const pendingID = "pending-restart-xyz"
	logger := logging.NewLogger("error")

	var gotCSRPEM string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if r.Method == http.MethodPost && r.URL.Path == "/api/v1/register" {
			var req registration.RegistrationRequest
			require.NoError(t, json.NewDecoder(r.Body).Decode(&req))
			gotCSRPEM = req.CSRPEM
			w.WriteHeader(http.StatusAccepted)
			_, _ = w.Write([]byte(`{"pending_id":"` + pendingID + `","steward_id":"steward-restarted","status":"pending"}`))
			return
		}
		// Verify the steward is polling the correct pending ID.
		assert.Contains(t, r.URL.Path, pendingID)
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"claimed","steward_id":"steward-restarted","tenant_id":"tenant-restart","transport_address":"ctrl.example.com:4433","client_cert":"CLIENT-CERT","ca_cert":"CA-CERT"}`))
	}))
	defer srv.Close()

	// === "Previous run": register (202 pending), then persist state — including the
	// CSR private key, not just the pending ID — as registerAndConnect does. ===
	preRestartClient, err := registration.NewHTTPClient(&registration.HTTPConfig{
		ControllerURL: srv.URL,
		Logger:        logger,
	})
	require.NoError(t, err)

	_, pendingResp, regErr := preRestartClient.Register(context.Background(), registration.RegistrationRequest{Token: "reg-token-restart"})
	require.NoError(t, regErr)
	require.NotNil(t, pendingResp)
	assert.Equal(t, pendingID, pendingResp.PendingID)
	assert.NotEmpty(t, gotCSRPEM, "the previous run must submit a CSR before dying")

	pendingKeyPEM, keyErr := preRestartClient.PendingClientKeyPEM()
	require.NoError(t, keyErr)
	require.NotEmpty(t, pendingKeyPEM)

	certStoreDir := t.TempDir()
	require.NoError(t, savePendingState(certStoreDir, PendingState{PendingID: pendingResp.PendingID, ClientKeyPEM: pendingKeyPEM}))

	// === Simulate restart: a brand-new process loads the persisted state and a
	// brand-new HTTPClient instance restores the key before resuming the poll. ===
	loaded, err := loadPendingState(certStoreDir)
	require.NoError(t, err)
	require.NotNil(t, loaded)
	require.NotEmpty(t, loaded.ClientKeyPEM, "the persisted pending state must carry the steward's private key across the simulated restart")

	resumedClient, err := registration.NewHTTPClient(&registration.HTTPConfig{
		ControllerURL: srv.URL,
		Logger:        logger,
	})
	require.NoError(t, err)
	require.NoError(t, resumedClient.ResumePendingClientKey(loaded.ClientKeyPEM),
		"the resumed process must restore the key before polling")

	// Resume polling with the loaded pending ID (no new registration call).
	result, pollErr := pollForApproval(
		context.Background(),
		resumedClient,
		loaded.PendingID,
		"reg-token-restart",
		30*time.Second,
		0, 0,
		logger,
	)

	require.NoError(t, pollErr)
	require.NotNil(t, result)
	assert.Equal(t, "steward-restarted", result.StewardID)
	assert.Equal(t, "CLIENT-CERT", result.ClientCert)
	require.NotEmpty(t, result.ClientKey,
		"the resumed process must produce a usable private key, not just a resumed pending_id — PR #3844 acceptance-review finding #1")
	assert.Equal(t, pendingKeyPEM, result.ClientKey,
		"the resumed process's credential must be paired with the same key generated by the process that died while quarantined")
}

// TestManualReviewFlow_Denied_ExitsWithClearMessage verifies that a "denied" response
// from the controller causes pollForApproval to return an error with a clear message.
func TestManualReviewFlow_Denied_ExitsWithClearMessage(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"denied"}`))
	}))
	defer srv.Close()

	httpClient, err := registration.NewHTTPClient(&registration.HTTPConfig{
		ControllerURL: srv.URL,
		Logger:        logging.NewLogger("error"),
	})
	require.NoError(t, err)

	result, pollErr := pollForApproval(
		context.Background(),
		httpClient,
		"pending-denied",
		"reg-token",
		5*time.Second,
		0, 0,
		logging.NewLogger("error"),
	)

	require.Error(t, pollErr)
	assert.Nil(t, result)
	assert.Contains(t, pollErr.Error(), "denied", "error must clearly state registration was denied")
}

// TestManualReviewFlow_PendingIDExpired_ReRegisters verifies that HTTP 410 Gone (pending
// record expired) causes pollForApproval to return (nil, nil) so the caller can re-register.
func TestManualReviewFlow_PendingIDExpired_ReRegisters(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusGone)
	}))
	defer srv.Close()

	httpClient, err := registration.NewHTTPClient(&registration.HTTPConfig{
		ControllerURL: srv.URL,
		Logger:        logging.NewLogger("error"),
	})
	require.NoError(t, err)

	certStoreDir := t.TempDir()
	require.NoError(t, savePendingState(certStoreDir, PendingState{PendingID: "pending-expired-id"}))

	result, pollErr := pollForApproval(
		context.Background(),
		httpClient,
		"pending-expired-id",
		"reg-token",
		5*time.Second,
		0, 0,
		logging.NewLogger("error"),
	)

	// nil result + nil error signals caller to re-register.
	assert.NoError(t, pollErr)
	assert.Nil(t, result, "nil result must signal re-registration is needed")
}
