// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: common/rbac.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubjectType defines the type of subject
type SubjectType int32

const (
	SubjectType_SUBJECT_TYPE_UNSPECIFIED SubjectType = 0
	SubjectType_SUBJECT_TYPE_USER        SubjectType = 1 // Human user
	SubjectType_SUBJECT_TYPE_SERVICE     SubjectType = 2 // Service account
	SubjectType_SUBJECT_TYPE_STEWARD     SubjectType = 3 // Steward instance
	SubjectType_SUBJECT_TYPE_API_CLIENT  SubjectType = 4 // API client
)

// Enum value maps for SubjectType.
var (
	SubjectType_name = map[int32]string{
		0: "SUBJECT_TYPE_UNSPECIFIED",
		1: "SUBJECT_TYPE_USER",
		2: "SUBJECT_TYPE_SERVICE",
		3: "SUBJECT_TYPE_STEWARD",
		4: "SUBJECT_TYPE_API_CLIENT",
	}
	SubjectType_value = map[string]int32{
		"SUBJECT_TYPE_UNSPECIFIED": 0,
		"SUBJECT_TYPE_USER":        1,
		"SUBJECT_TYPE_SERVICE":     2,
		"SUBJECT_TYPE_STEWARD":     3,
		"SUBJECT_TYPE_API_CLIENT":  4,
	}
)

func (x SubjectType) Enum() *SubjectType {
	p := new(SubjectType)
	*p = x
	return p
}

func (x SubjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_rbac_proto_enumTypes[0].Descriptor()
}

func (SubjectType) Type() protoreflect.EnumType {
	return &file_common_rbac_proto_enumTypes[0]
}

func (x SubjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubjectType.Descriptor instead.
func (SubjectType) EnumDescriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{0}
}

// Permission represents a specific action that can be performed
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // Unique permission identifier (e.g., "steward.register")
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                     // Human-readable name
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                       // Description of what this permission allows
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // Type of resource (steward, configuration, tenant)
	Actions       []string               `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`                               // Allowed actions (create, read, update, delete, execute)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_common_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_common_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Permission) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// Role represents a collection of permissions
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Unique role identifier
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // Human-readable role name
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                          // Role description
	PermissionIds []string               `protobuf:"bytes,4,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"` // Permission IDs assigned to this role
	IsSystemRole  bool                   `protobuf:"varint,5,opt,name=is_system_role,json=isSystemRole,proto3" json:"is_system_role,omitempty"` // Whether this is a built-in system role
	TenantId      string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                // Tenant scope (empty for system-wide roles)
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`            // Creation timestamp
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`            // Last update timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_common_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_common_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *Role) GetIsSystemRole() bool {
	if x != nil {
		return x.IsSystemRole
	}
	return false
}

func (x *Role) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Role) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Role) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Subject represents an entity that can have roles assigned
type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                           // Unique subject identifier
	Type          SubjectType            `protobuf:"varint,2,opt,name=type,proto3,enum=cfgms.api.common.SubjectType" json:"type,omitempty"`                                                    // Type of subject
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`                                                      // Human-readable name
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                               // Primary tenant association
	RoleIds       []string               `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`                                                                  // Assigned role IDs
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional attributes for ABAC
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                                                              // Whether subject is active
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                           // Creation timestamp
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                           // Last update timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_common_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_common_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetType() SubjectType {
	if x != nil {
		return x.Type
	}
	return SubjectType_SUBJECT_TYPE_UNSPECIFIED
}

func (x *Subject) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Subject) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Subject) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *Subject) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Subject) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Subject) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Subject) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// RoleAssignment represents the assignment of a role to a subject
type RoleAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                    // Unique assignment identifier
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`     // Subject receiving the role
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`              // Role being assigned
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`        // Tenant scope for this assignment
	Conditions    []string               `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`                    // Optional conditions (ABAC support)
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`    // Optional expiration timestamp
	AssignedAt    int64                  `protobuf:"varint,7,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"` // Assignment timestamp
	AssignedBy    string                 `protobuf:"bytes,8,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`  // Who made the assignment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignment) Reset() {
	*x = RoleAssignment{}
	mi := &file_common_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignment) ProtoMessage() {}

func (x *RoleAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_common_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignment.ProtoReflect.Descriptor instead.
func (*RoleAssignment) Descriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *RoleAssignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleAssignment) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *RoleAssignment) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleAssignment) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RoleAssignment) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *RoleAssignment) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RoleAssignment) GetAssignedAt() int64 {
	if x != nil {
		return x.AssignedAt
	}
	return 0
}

func (x *RoleAssignment) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

// AccessRequest represents a request for permission checking
type AccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`                                                      // Subject requesting access
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`                                             // Permission being requested
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`                                                   // Specific resource (optional)
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                         // Tenant context
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context for ABAC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_common_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *AccessRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AccessRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *AccessRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AccessRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// AccessResponse represents the result of permission checking
type AccessResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Granted            bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`                                                // Whether access is granted
	Reason             string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                                   // Reason for the decision
	AppliedRoles       []string               `protobuf:"bytes,3,rep,name=applied_roles,json=appliedRoles,proto3" json:"applied_roles,omitempty"`                   // Roles that granted access
	AppliedPermissions []string               `protobuf:"bytes,4,rep,name=applied_permissions,json=appliedPermissions,proto3" json:"applied_permissions,omitempty"` // Permissions that granted access
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	mi := &file_common_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *AccessResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *AccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AccessResponse) GetAppliedRoles() []string {
	if x != nil {
		return x.AppliedRoles
	}
	return nil
}

func (x *AccessResponse) GetAppliedPermissions() []string {
	if x != nil {
		return x.AppliedPermissions
	}
	return nil
}

// AuthorizationContext provides context for authorization decisions
type AuthorizationContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantId           string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                                                                         // Current tenant context
	SubjectId          string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`                                                                                                      // Subject making the request
	Environment        map[string]string      `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                                         // Environment attributes (IP, time, etc.)
	ResourceAttributes map[string]string      `protobuf:"bytes,4,rep,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Resource-specific attributes
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthorizationContext) Reset() {
	*x = AuthorizationContext{}
	mi := &file_common_rbac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationContext) ProtoMessage() {}

func (x *AuthorizationContext) ProtoReflect() protoreflect.Message {
	mi := &file_common_rbac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationContext.ProtoReflect.Descriptor instead.
func (*AuthorizationContext) Descriptor() ([]byte, []int) {
	return file_common_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizationContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthorizationContext) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *AuthorizationContext) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *AuthorizationContext) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

var File_common_rbac_proto protoreflect.FileDescriptor

const file_common_rbac_proto_rawDesc = "" +
	"\n" +
	"\x11common/rbac.proto\x12\x10cfgms.api.common\"\x91\x01\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x18\n" +
	"\aactions\x18\x05 \x03(\tR\aactions\"\xf4\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0epermission_ids\x18\x04 \x03(\tR\rpermissionIds\x12$\n" +
	"\x0eis_system_role\x18\x05 \x01(\bR\fisSystemRole\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\x8c\x03\n" +
	"\aSubject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.cfgms.api.common.SubjectTypeR\x04type\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x19\n" +
	"\brole_ids\x18\x05 \x03(\tR\aroleIds\x12I\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2).cfgms.api.common.Subject.AttributesEntryR\n" +
	"attributes\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x0eRoleAssignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1e\n" +
	"\n" +
	"conditions\x18\x05 \x03(\tR\n" +
	"conditions\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x1f\n" +
	"\vassigned_at\x18\a \x01(\x03R\n" +
	"assignedAt\x12\x1f\n" +
	"\vassigned_by\x18\b \x01(\tR\n" +
	"assignedBy\"\x95\x02\n" +
	"\rAccessRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12F\n" +
	"\acontext\x18\x05 \x03(\v2,.cfgms.api.common.AccessRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\x0eAccessResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12#\n" +
	"\rapplied_roles\x18\x03 \x03(\tR\fappliedRoles\x12/\n" +
	"\x13applied_permissions\x18\x04 \x03(\tR\x12appliedPermissions\"\xa5\x03\n" +
	"\x14AuthorizationContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12Y\n" +
	"\venvironment\x18\x03 \x03(\v27.cfgms.api.common.AuthorizationContext.EnvironmentEntryR\venvironment\x12o\n" +
	"\x13resource_attributes\x18\x04 \x03(\v2>.cfgms.api.common.AuthorizationContext.ResourceAttributesEntryR\x12resourceAttributes\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17ResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x93\x01\n" +
	"\vSubjectType\x12\x1c\n" +
	"\x18SUBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SUBJECT_TYPE_USER\x10\x01\x12\x18\n" +
	"\x14SUBJECT_TYPE_SERVICE\x10\x02\x12\x18\n" +
	"\x14SUBJECT_TYPE_STEWARD\x10\x03\x12\x1b\n" +
	"\x17SUBJECT_TYPE_API_CLIENT\x10\x04B)Z'github.com/cfgis/cfgms/api/proto/commonb\x06proto3"

var (
	file_common_rbac_proto_rawDescOnce sync.Once
	file_common_rbac_proto_rawDescData []byte
)

func file_common_rbac_proto_rawDescGZIP() []byte {
	file_common_rbac_proto_rawDescOnce.Do(func() {
		file_common_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_rbac_proto_rawDesc), len(file_common_rbac_proto_rawDesc)))
	})
	return file_common_rbac_proto_rawDescData
}

var file_common_rbac_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_rbac_proto_goTypes = []any{
	(SubjectType)(0),             // 0: cfgms.api.common.SubjectType
	(*Permission)(nil),           // 1: cfgms.api.common.Permission
	(*Role)(nil),                 // 2: cfgms.api.common.Role
	(*Subject)(nil),              // 3: cfgms.api.common.Subject
	(*RoleAssignment)(nil),       // 4: cfgms.api.common.RoleAssignment
	(*AccessRequest)(nil),        // 5: cfgms.api.common.AccessRequest
	(*AccessResponse)(nil),       // 6: cfgms.api.common.AccessResponse
	(*AuthorizationContext)(nil), // 7: cfgms.api.common.AuthorizationContext
	nil,                          // 8: cfgms.api.common.Subject.AttributesEntry
	nil,                          // 9: cfgms.api.common.AccessRequest.ContextEntry
	nil,                          // 10: cfgms.api.common.AuthorizationContext.EnvironmentEntry
	nil,                          // 11: cfgms.api.common.AuthorizationContext.ResourceAttributesEntry
}
var file_common_rbac_proto_depIdxs = []int32{
	0,  // 0: cfgms.api.common.Subject.type:type_name -> cfgms.api.common.SubjectType
	8,  // 1: cfgms.api.common.Subject.attributes:type_name -> cfgms.api.common.Subject.AttributesEntry
	9,  // 2: cfgms.api.common.AccessRequest.context:type_name -> cfgms.api.common.AccessRequest.ContextEntry
	10, // 3: cfgms.api.common.AuthorizationContext.environment:type_name -> cfgms.api.common.AuthorizationContext.EnvironmentEntry
	11, // 4: cfgms.api.common.AuthorizationContext.resource_attributes:type_name -> cfgms.api.common.AuthorizationContext.ResourceAttributesEntry
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_common_rbac_proto_init() }
func file_common_rbac_proto_init() {
	if File_common_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_rbac_proto_rawDesc), len(file_common_rbac_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_rbac_proto_goTypes,
		DependencyIndexes: file_common_rbac_proto_depIdxs,
		EnumInfos:         file_common_rbac_proto_enumTypes,
		MessageInfos:      file_common_rbac_proto_msgTypes,
	}.Build()
	File_common_rbac_proto = out.File
	file_common_rbac_proto_goTypes = nil
	file_common_rbac_proto_depIdxs = nil
}
