// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Jordan Ritz
package cutover

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/cfgis/cfgms/pkg/cert"
)

// HTTPSmoketester is the production Smoketester. It probes a candidate
// controller backend by:
//
//  1. Waiting up to ReadyTimeout for the candidate's API port to accept
//     connections (using waitForPortReady).
//  2. Issuing a GET to https://<candidateAPIAddr>/api/v1/ready and
//     requiring a 200. /api/v1/ready is the controller's REAL-STATE
//     readiness probe (Issue #2012): the handler round-trips the durable
//     DNA fleet store, so a 200 proves the candidate can actually serve,
//     not merely that its API objects are wired (which is all the old
//     /api/v1/health liveness check confirmed). A 503 (storage
//     unreachable) or any non-200 is a smoketest FAILURE — the
//     orchestrator must not promote a controller that cannot serve.
//
// The probe deliberately does NOT require valid client certs (the
// readiness endpoint is unauthenticated), because the goal is to confirm
// the new binary can serve from storage, not to authenticate against it.
//
// What this DOES NOT cover (deferred per the original story scope):
//
//   - "green serves a synthetic registration request correctly" and
//     "green handles a gRPC stream from a synthetic steward" — follow-ups
//     that need a short-lived registration token / fake-steward harness.
//     They DON'T change the Smoketester contract; they just extend Probe.
type HTTPSmoketester struct {
	// ReadyTimeout caps how long Probe waits for the candidate to start
	// accepting TCP connections. Default 20s. The controller's startup
	// (cert load + storage init + listener bind) typically completes in
	// 1-3s; 20s leaves headroom for slow disks.
	ReadyTimeout time.Duration

	// RequestTimeout caps individual HTTP request duration. Default 5s.
	RequestTimeout time.Duration

	// SkipTLSVerify when true accepts the self-signed cert the
	// controller uses by default. Production callers leave this false
	// IF they have a CA bundle to trust; tests typically set true.
	// In the cutover flow blue and green share the same CA (Story B
	// substrate), so a CA-aware caller can verify with full chain.
	SkipTLSVerify bool
}

// Probe implements Smoketester. listenAPIAddr is the address the
// candidate is currently bound on (the candidate ports during the
// pre-cutover smoketest, or the canonical ports during the post-swap
// readiness check). listenTransportAddr is currently unused by the
// HTTP path but is part of the Smoketester contract for future RPC-
// based probes.
func (h *HTTPSmoketester) Probe(ctx context.Context, _ ProcessHandle, listenAPIAddr, _ string) error {
	readyTO := h.ReadyTimeout
	if readyTO <= 0 {
		readyTO = 20 * time.Second
	}
	reqTO := h.RequestTimeout
	if reqTO <= 0 {
		reqTO = 5 * time.Second
	}

	// Step 1: wait for the candidate's API port to accept connections.
	readyCtx, cancel := context.WithTimeout(ctx, readyTO)
	defer cancel()
	if err := waitForPortReady(readyCtx, listenAPIAddr, readyTO); err != nil {
		return fmt.Errorf("smoketest: candidate API not listening: %w", err)
	}

	// Step 2: GET /api/v1/ready over TLS and require 200. Self-signed cert
	// is tolerated because the controller's REST cert is auto-generated by
	// default and the probe authenticates the SERVER's readiness, not its
	// identity. /api/v1/ready round-trips durable storage, so a 200 means
	// the candidate can actually serve — the real-state gate (Issue #2012).
	probeAddr := normalizeProbeAddr(listenAPIAddr)
	probeURL := "https://" + probeAddr + "/api/v1/ready"
	client := &http.Client{
		Timeout: reqTO,
		Transport: &http.Transport{
			TLSClientConfig: cert.CreateProbeClientTLSConfig(h.SkipTLSVerify),
		},
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, probeURL, nil)
	if err != nil {
		return fmt.Errorf("smoketest: build request: %w", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("smoketest: GET %s: %w", probeURL, err)
	}
	defer func() { _ = resp.Body.Close() }()

	// 200 = the candidate is ready (storage round-trip succeeded). Anything
	// else — notably 503 (storage unreachable) — is a smoketest failure; the
	// orchestrator must not promote a controller that cannot serve.
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("smoketest: GET %s returned status %d (want 200 ready)", probeURL, resp.StatusCode)
	}
	return nil
}
