// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026 Jordan Ritz
package cutover

import (
	"context"
	"crypto/tls"
	"fmt"
	"net/http"
	"time"
)

// HTTPSmoketester is the production Smoketester. It probes a candidate
// controller backend by:
//
//  1. Waiting up to ReadyTimeout for the candidate's API port to accept
//     connections (using waitForPortReady).
//  2. Issuing a GET to https://<candidateAPIAddr>/healthz. The
//     controller's REST API exposes /healthz for unauthenticated
//     liveness checks. A 200 OR 401 (auth-required) response counts as
//     "the API is up" — we don't carry an admin bundle so a 401 is the
//     successful signal that mTLS is wired and the router is serving.
//
// The probe deliberately does NOT require valid client certs, because
// the goal is to confirm "the new binary is listening + the API
// process is alive," not to authenticate against it. Future work could
// extend this to send a real signed admin request and inspect the
// JSON envelope.
//
// What this DOES NOT cover (deferred per the original story scope):
//
//   - "green serves a synthetic registration request correctly" — the
//     spec asks for a real registration RPC against the candidate. The
//     smoketester surface accommodates that (it's just a more
//     elaborate Probe impl); landing a synthetic-registration probe is
//     a follow-up because it requires minting a short-lived registration
//     token at probe time and tearing it down afterwards.
//   - "green handles a gRPC stream from a synthetic steward" — same
//     follow-up; needs a fake-steward client harness.
//
// These follow-ups DON'T change the Smoketester contract; they just
// extend the Probe body.
type HTTPSmoketester struct {
	// ReadyTimeout caps how long Probe waits for the candidate to start
	// accepting TCP connections. Default 20s. The controller's startup
	// (cert load + storage init + listener bind) typically completes in
	// 1-3s; 20s leaves headroom for slow disks.
	ReadyTimeout time.Duration

	// RequestTimeout caps individual HTTP request duration. Default 5s.
	RequestTimeout time.Duration

	// SkipTLSVerify when true accepts the self-signed cert the
	// controller uses by default. Production callers leave this false
	// IF they have a CA bundle to trust; tests typically set true.
	// In the cutover flow blue and green share the same CA (Story B
	// substrate), so a CA-aware caller can verify with full chain.
	SkipTLSVerify bool
}

// Probe implements Smoketester. listenAPIAddr is the address the
// candidate is currently bound on (the candidate ports during the
// pre-cutover smoketest, or the canonical ports during the post-swap
// readiness check). listenTransportAddr is currently unused by the
// HTTP path but is part of the Smoketester contract for future RPC-
// based probes.
func (h *HTTPSmoketester) Probe(ctx context.Context, _ ProcessHandle, listenAPIAddr, _ string) error {
	readyTO := h.ReadyTimeout
	if readyTO <= 0 {
		readyTO = 20 * time.Second
	}
	reqTO := h.RequestTimeout
	if reqTO <= 0 {
		reqTO = 5 * time.Second
	}

	// Step 1: wait for the candidate's API port to accept connections.
	readyCtx, cancel := context.WithTimeout(ctx, readyTO)
	defer cancel()
	if err := waitForPortReady(readyCtx, listenAPIAddr, readyTO); err != nil {
		return fmt.Errorf("smoketest: candidate API not listening: %w", err)
	}

	// Step 2: GET /healthz over TLS. Self-signed cert is tolerated
	// because the controller's REST cert is auto-generated by default
	// and the probe doesn't need to authenticate the SERVER; it just
	// needs to confirm the API process is up.
	probeAddr := normalizeProbeAddr(listenAPIAddr)
	probeURL := "https://" + probeAddr + "/healthz"
	client := &http.Client{
		Timeout: reqTO,
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				//#nosec G402 -- smoketest acknowledges the cert is self-signed; we're probing liveness not authenticating
				InsecureSkipVerify: h.SkipTLSVerify,
				MinVersion:         tls.VersionTLS12,
			},
		},
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, probeURL, nil)
	if err != nil {
		return fmt.Errorf("smoketest: build request: %w", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("smoketest: GET %s: %w", probeURL, err)
	}
	defer resp.Body.Close()

	// 200 OK = healthy. 401 / 403 = auth-required which still proves
	// the API is serving (the mTLS layer answered). Any other code,
	// including a connection error masquerading as a low 5xx, is a
	// smoketest failure.
	switch {
	case resp.StatusCode == http.StatusOK:
		return nil
	case resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusForbidden:
		return nil
	default:
		return fmt.Errorf("smoketest: GET %s returned status %d (want 200/401/403)", probeURL, resp.StatusCode)
	}
}
