#!/usr/bin/env bash
#
# generate-invalid-test-certs.sh - Generate INVALID certificates for negative testing
#
# This script generates ONLY intentionally-invalid certificates used to test that
# the MQTT broker correctly rejects bad certificates (expired, self-signed, wrong-CA).
#
# IMPORTANT: This script does NOT generate valid certificates. Valid certificates
# (CA, server, client) are generated by the Controller using native certificate
# management (pkg/cert) via the certificate.auto_generate config option.
#
# Valid certificates are generated by:
# 1. Local development: make generate-test-certificates
# 2. CI/CD: Controller auto-generation in GitHub Actions workflow
# 3. Production: Controller auto-generation on first boot
#
# See:
# - test/integration/configs/controller-test.yaml (certificate config)
# - features/controller/server/server.go::initializeCertificateManager()
# - pkg/cert/ (native certificate management library)
#
# Story #109: Re-enable GitHub Actions Workflows
#
# Usage:
#   ./scripts/generate-invalid-test-certs.sh [output_dir]
#
# Arguments:
#   output_dir  - Directory to store generated certificates (default: test/integration/mqtt_quic/certs)

set -euo pipefail

# Configuration
OUTPUT_DIR="${1:-test/integration/mqtt_quic/certs}"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}[INFO]${NC} Generating invalid certificates for negative testing..."
echo -e "${GREEN}[INFO]${NC} Output directory: ${OUTPUT_DIR}"
echo ""
echo -e "${YELLOW}[NOTE]${NC} Valid certificates (CA, server, client) are generated"
echo -e "${YELLOW}[NOTE]${NC} by Controller via certificate.auto_generate config option"
echo ""

# Ensure output directory exists
mkdir -p "${OUTPUT_DIR}"

# =============================================================================
# 1. Expired Certificate (for testing certificate expiration rejection)
# =============================================================================
echo -e "${GREEN}[INFO]${NC} Generating expired certificate..."

openssl genrsa -out "${OUTPUT_DIR}/expired-key.pem" 2048 2>/dev/null

# Generate self-signed expired certificate (testing expiration, not CA chain)
# Use faketime if available to backdate certificate
if command -v faketime &> /dev/null; then
    faketime 'yesterday' openssl req -new -x509 \
        -key "${OUTPUT_DIR}/expired-key.pem" \
        -out "${OUTPUT_DIR}/expired-cert.pem" \
        -days 1 \
        -subj "/C=US/ST=Test/L=TestCity/O=CFGMS Test/OU=Test Expired/CN=expired-client" \
        2>/dev/null
    echo -e "${GREEN}[INFO]${NC} ✓ Expired certificate generated (backdated with faketime)"
else
    # Without faketime, generate 1-day self-signed cert
    openssl req -new -x509 \
        -key "${OUTPUT_DIR}/expired-key.pem" \
        -out "${OUTPUT_DIR}/expired-cert.pem" \
        -days 1 \
        -subj "/C=US/ST=Test/L=TestCity/O=CFGMS Test/OU=Test Expired/CN=expired-client" \
        2>/dev/null
    echo -e "${YELLOW}[WARN]${NC} faketime not available, generated 1-day cert instead"
    echo -e "${GREEN}[INFO]${NC} ✓ Short-lived certificate generated"
fi

# =============================================================================
# 2. Self-Signed Certificate (for testing CA validation)
# =============================================================================
echo -e "${GREEN}[INFO]${NC} Generating self-signed certificate..."

openssl genrsa -out "${OUTPUT_DIR}/selfsigned-key.pem" 2048 2>/dev/null
openssl req -new -x509 \
    -key "${OUTPUT_DIR}/selfsigned-key.pem" \
    -out "${OUTPUT_DIR}/selfsigned-cert.pem" \
    -days 365 \
    -subj "/C=US/ST=Test/L=TestCity/O=CFGMS Test/OU=Self Signed/CN=selfsigned-client" \
    2>/dev/null

echo -e "${GREEN}[INFO]${NC} ✓ Self-signed certificate generated"

# =============================================================================
# 3. Wrong CA Certificate (for testing CA trust chain validation)
# =============================================================================
echo -e "${GREEN}[INFO]${NC} Generating wrong CA certificate..."

# Generate a different CA
openssl genrsa -out "${OUTPUT_DIR}/wrong-ca-key.pem" 4096 2>/dev/null
openssl req -new -x509 \
    -key "${OUTPUT_DIR}/wrong-ca-key.pem" \
    -out "${OUTPUT_DIR}/wrong-ca-cert.pem" \
    -days 3650 \
    -subj "/C=US/ST=Test/L=TestCity/O=Wrong CA/OU=Test CA/CN=Wrong CA" \
    2>/dev/null

echo -e "${GREEN}[INFO]${NC} ✓ Wrong CA certificate generated"

# Generate client certificate signed by wrong CA
echo -e "${GREEN}[INFO]${NC} Generating client certificate signed by wrong CA..."

openssl genrsa -out "${OUTPUT_DIR}/wrong-ca-client-key.pem" 2048 2>/dev/null
openssl req -new \
    -key "${OUTPUT_DIR}/wrong-ca-client-key.pem" \
    -out "${OUTPUT_DIR}/wrong-ca-client-csr.pem" \
    -subj "/C=US/ST=Test/L=TestCity/O=CFGMS Test/OU=Wrong CA Client/CN=wrong-ca-client" \
    2>/dev/null

openssl x509 -req \
    -in "${OUTPUT_DIR}/wrong-ca-client-csr.pem" \
    -CA "${OUTPUT_DIR}/wrong-ca-cert.pem" \
    -CAkey "${OUTPUT_DIR}/wrong-ca-key.pem" \
    -CAcreateserial \
    -out "${OUTPUT_DIR}/wrong-ca-client-cert.pem" \
    -days 365 \
    2>/dev/null

echo -e "${GREEN}[INFO]${NC} ✓ Wrong CA client certificate generated"

# Cleanup CSR and serial files
rm -f "${OUTPUT_DIR}/wrong-ca-client-csr.pem"
rm -f "${OUTPUT_DIR}"/*.srl

# =============================================================================
# Set Permissions
# =============================================================================
echo -e "${GREEN}[INFO]${NC} Setting file permissions..."

# Private keys should be readable only by owner
chmod 600 "${OUTPUT_DIR}"/expired-key.pem \
          "${OUTPUT_DIR}"/selfsigned-key.pem \
          "${OUTPUT_DIR}"/wrong-ca-key.pem \
          "${OUTPUT_DIR}"/wrong-ca-client-key.pem 2>/dev/null || true

# Certificates should be readable by all
chmod 644 "${OUTPUT_DIR}"/expired-cert.pem \
          "${OUTPUT_DIR}"/selfsigned-cert.pem \
          "${OUTPUT_DIR}"/wrong-ca-cert.pem \
          "${OUTPUT_DIR}"/wrong-ca-client-cert.pem 2>/dev/null || true

echo -e "${GREEN}[INFO]${NC} ✓ File permissions set"

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Invalid Certificate Generation Complete${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${GREEN}[INFO]${NC} Generated invalid certificates:"
echo -e "${GREEN}[INFO]${NC}   • expired-cert.pem / expired-key.pem"
echo -e "${GREEN}[INFO]${NC}   • selfsigned-cert.pem / selfsigned-key.pem"
echo -e "${GREEN}[INFO]${NC}   • wrong-ca-cert.pem / wrong-ca-key.pem"
echo -e "${GREEN}[INFO]${NC}   • wrong-ca-client-cert.pem / wrong-ca-client-key.pem"
echo ""
echo -e "${GREEN}[INFO]${NC} All certificates stored in: ${OUTPUT_DIR}"
echo ""
echo -e "${YELLOW}[NOTE]${NC} These certificates are for TESTING ONLY!"
echo -e "${YELLOW}[NOTE]${NC} They validate that the MQTT broker correctly rejects invalid certificates."
echo ""
