// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: clusterdelivery/delivery.proto

package clusterdelivery

import (
	transport "github.com/cfgis/cfgms/api/proto/transport"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliverCommandRequest carries the target steward and the full signed
// command envelope, wire-encoded exactly as pkg/controlplane/providers/grpc
// encodes it for direct steward delivery (see convert.go's
// SignedCommandToProto/SignedCommandFromProto) — the receiving node decodes
// it and hands it to its own local SendCommand path unchanged.
type DeliverCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StewardId     string                 `protobuf:"bytes,1,opt,name=steward_id,json=stewardId,proto3" json:"steward_id,omitempty"`
	Command       *transport.Command     `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverCommandRequest) Reset() {
	*x = DeliverCommandRequest{}
	mi := &file_clusterdelivery_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverCommandRequest) ProtoMessage() {}

func (x *DeliverCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusterdelivery_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverCommandRequest.ProtoReflect.Descriptor instead.
func (*DeliverCommandRequest) Descriptor() ([]byte, []int) {
	return file_clusterdelivery_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverCommandRequest) GetStewardId() string {
	if x != nil {
		return x.StewardId
	}
	return ""
}

func (x *DeliverCommandRequest) GetCommand() *transport.Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// DeliverCommandResponse reports whether the receiving node's local registry
// held a connection for the requested steward and attempted local delivery.
type DeliverCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// delivered is true only when the receiving node found a live local
	// connection for the steward and its local SendCommand call succeeded.
	Delivered bool `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	// not_connected is true when the receiving node has no live local
	// connection for the steward (e.g. it disconnected between the caller's
	// routing-table lookup and this call). The caller falls back to the
	// durable outbox in this case rather than treating it as a transport error.
	NotConnected bool `protobuf:"varint,2,opt,name=not_connected,json=notConnected,proto3" json:"not_connected,omitempty"`
	// message carries a human-readable detail for logging/diagnostics only;
	// callers must not branch on its contents.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverCommandResponse) Reset() {
	*x = DeliverCommandResponse{}
	mi := &file_clusterdelivery_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverCommandResponse) ProtoMessage() {}

func (x *DeliverCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusterdelivery_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverCommandResponse.ProtoReflect.Descriptor instead.
func (*DeliverCommandResponse) Descriptor() ([]byte, []int) {
	return file_clusterdelivery_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverCommandResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *DeliverCommandResponse) GetNotConnected() bool {
	if x != nil {
		return x.NotConnected
	}
	return false
}

func (x *DeliverCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_clusterdelivery_delivery_proto protoreflect.FileDescriptor

const file_clusterdelivery_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1eclusterdelivery/delivery.proto\x12\x15cfgms.clusterdelivery\x1a\x17transport/control.proto\"j\n" +
	"\x15DeliverCommandRequest\x12\x1d\n" +
	"\n" +
	"steward_id\x18\x01 \x01(\tR\tstewardId\x122\n" +
	"\acommand\x18\x02 \x01(\v2\x18.cfgms.transport.CommandR\acommand\"u\n" +
	"\x16DeliverCommandResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12#\n" +
	"\rnot_connected\x18\x02 \x01(\bR\fnotConnected\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x80\x01\n" +
	"\x0fDeliveryService\x12m\n" +
	"\x0eDeliverCommand\x12,.cfgms.clusterdelivery.DeliverCommandRequest\x1a-.cfgms.clusterdelivery.DeliverCommandResponseB2Z0github.com/cfgis/cfgms/api/proto/clusterdeliveryb\x06proto3"

var (
	file_clusterdelivery_delivery_proto_rawDescOnce sync.Once
	file_clusterdelivery_delivery_proto_rawDescData []byte
)

func file_clusterdelivery_delivery_proto_rawDescGZIP() []byte {
	file_clusterdelivery_delivery_proto_rawDescOnce.Do(func() {
		file_clusterdelivery_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusterdelivery_delivery_proto_rawDesc), len(file_clusterdelivery_delivery_proto_rawDesc)))
	})
	return file_clusterdelivery_delivery_proto_rawDescData
}

var file_clusterdelivery_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clusterdelivery_delivery_proto_goTypes = []any{
	(*DeliverCommandRequest)(nil),  // 0: cfgms.clusterdelivery.DeliverCommandRequest
	(*DeliverCommandResponse)(nil), // 1: cfgms.clusterdelivery.DeliverCommandResponse
	(*transport.Command)(nil),      // 2: cfgms.transport.Command
}
var file_clusterdelivery_delivery_proto_depIdxs = []int32{
	2, // 0: cfgms.clusterdelivery.DeliverCommandRequest.command:type_name -> cfgms.transport.Command
	0, // 1: cfgms.clusterdelivery.DeliveryService.DeliverCommand:input_type -> cfgms.clusterdelivery.DeliverCommandRequest
	1, // 2: cfgms.clusterdelivery.DeliveryService.DeliverCommand:output_type -> cfgms.clusterdelivery.DeliverCommandResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clusterdelivery_delivery_proto_init() }
func file_clusterdelivery_delivery_proto_init() {
	if File_clusterdelivery_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusterdelivery_delivery_proto_rawDesc), len(file_clusterdelivery_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusterdelivery_delivery_proto_goTypes,
		DependencyIndexes: file_clusterdelivery_delivery_proto_depIdxs,
		MessageInfos:      file_clusterdelivery_delivery_proto_msgTypes,
	}.Build()
	File_clusterdelivery_delivery_proto = out.File
	file_clusterdelivery_delivery_proto_goTypes = nil
	file_clusterdelivery_delivery_proto_depIdxs = nil
}
