// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: clusterdelivery/delivery.proto

package clusterdelivery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_DeliverCommand_FullMethodName = "/cfgms.clusterdelivery.DeliveryService/DeliverCommand"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeliveryService is the internal controller-to-controller delivery RPC
// (ADR-031 Decision 3, Issue #3764) — the first inter-node RPC other than
// Raft's own transport. It lets a controller node that does not hold a
// steward's control-plane connection ask the node that does to deliver a
// command immediately, without waiting for the steward to poll or reconnect.
//
// mTLS-secured on the internal listener using the same certificate
// infrastructure as the Raft transport (pkg/cert.Manager); this service mints
// no new PKI of its own. The handshake alone does NOT establish a peer-node
// caller: that listener's trust anchor is the controller CA, which also signs
// every steward and admin client certificate. Authorization is therefore an
// application-layer check — the caller must present a client certificate whose
// CommonName is a known cluster node ID (internaldelivery.PeerAuthorizer),
// mirroring the CN allowlist the Raft transport applies on its own listener.
// Steward and admin certificates are refused with PERMISSION_DENIED.
type DeliveryServiceClient interface {
	// DeliverCommand asks the receiving node to deliver command to the steward
	// named by steward_id using ITS OWN local control-plane connection. The
	// response acknowledges that the receiving node's local registry holds (or
	// does not hold) a connection for the steward and that a local delivery
	// attempt was made — not that the steward itself has received or executed
	// the command, which remains async and is tracked separately via the
	// durable outbox (Issue #3757).
	DeliverCommand(ctx context.Context, in *DeliverCommandRequest, opts ...grpc.CallOption) (*DeliverCommandResponse, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) DeliverCommand(ctx context.Context, in *DeliverCommandRequest, opts ...grpc.CallOption) (*DeliverCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverCommandResponse)
	err := c.cc.Invoke(ctx, DeliveryService_DeliverCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
//
// DeliveryService is the internal controller-to-controller delivery RPC
// (ADR-031 Decision 3, Issue #3764) — the first inter-node RPC other than
// Raft's own transport. It lets a controller node that does not hold a
// steward's control-plane connection ask the node that does to deliver a
// command immediately, without waiting for the steward to poll or reconnect.
//
// mTLS-secured on the internal listener using the same certificate
// infrastructure as the Raft transport (pkg/cert.Manager); this service mints
// no new PKI of its own. The handshake alone does NOT establish a peer-node
// caller: that listener's trust anchor is the controller CA, which also signs
// every steward and admin client certificate. Authorization is therefore an
// application-layer check — the caller must present a client certificate whose
// CommonName is a known cluster node ID (internaldelivery.PeerAuthorizer),
// mirroring the CN allowlist the Raft transport applies on its own listener.
// Steward and admin certificates are refused with PERMISSION_DENIED.
type DeliveryServiceServer interface {
	// DeliverCommand asks the receiving node to deliver command to the steward
	// named by steward_id using ITS OWN local control-plane connection. The
	// response acknowledges that the receiving node's local registry holds (or
	// does not hold) a connection for the steward and that a local delivery
	// attempt was made — not that the steward itself has received or executed
	// the command, which remains async and is tracked separately via the
	// durable outbox (Issue #3757).
	DeliverCommand(context.Context, *DeliverCommandRequest) (*DeliverCommandResponse, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) DeliverCommand(context.Context, *DeliverCommandRequest) (*DeliverCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverCommand not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_DeliverCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).DeliverCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_DeliverCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).DeliverCommand(ctx, req.(*DeliverCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cfgms.clusterdelivery.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverCommand",
			Handler:    _DeliveryService_DeliverCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clusterdelivery/delivery.proto",
}
