// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 CFGMS Contributors
package e2e

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/suite"

	"github.com/cfgis/cfgms/features/terminal"
)

// SyntheticMonitoringSuite provides ongoing validation for production environments
type SyntheticMonitoringSuite struct {
	suite.Suite
	framework       *E2ETestFramework
	terminalManager terminal.SessionManager
	httpClient      *http.Client
	monitoringData  *SyntheticMonitoringData
}

// SyntheticMonitoringData tracks monitoring metrics over time
type SyntheticMonitoringData struct {
	TestResults   map[string][]SyntheticTestResult `json:"test_results"`
	Alerts        []SyntheticAlert                 `json:"alerts"`
	SystemMetrics SystemMetrics                    `json:"system_metrics"`
	LastUpdate    time.Time                        `json:"last_update"`
	mu            sync.RWMutex
}

// SyntheticTestResult represents a single synthetic test execution
type SyntheticTestResult struct {
	TestName     string                 `json:"test_name"`
	Timestamp    time.Time              `json:"timestamp"`
	Success      bool                   `json:"success"`
	ResponseTime time.Duration          `json:"response_time"`
	ErrorMessage string                 `json:"error_message,omitempty"`
	Metrics      map[string]interface{} `json:"metrics,omitempty"`
}

// SyntheticAlert represents an alert generated by synthetic monitoring
type SyntheticAlert struct {
	AlertID   string                 `json:"alert_id"`
	Severity  string                 `json:"severity"` // critical, warning, info
	Message   string                 `json:"message"`
	TestName  string                 `json:"test_name"`
	Timestamp time.Time              `json:"timestamp"`
	Resolved  bool                   `json:"resolved"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
}

// SystemMetrics tracks overall system health
type SystemMetrics struct {
	AvailabilityPercent float64           `json:"availability_percent"`
	AverageResponseTime time.Duration     `json:"average_response_time"`
	ErrorRate           float64           `json:"error_rate"`
	ActiveSessions      int               `json:"active_sessions"`
	TotalRequests       int64             `json:"total_requests"`
	LastHealthCheck     time.Time         `json:"last_health_check"`
	ComponentStatus     map[string]string `json:"component_status"`
}

// SetupSuite initializes synthetic monitoring
func (s *SyntheticMonitoringSuite) SetupSuite() {
	config := CIOptimizedConfig()
	config.PerformanceMode = true
	config.TestDataSize = "small" // Lightweight for continuous monitoring
	config.TestTimeout = 5 * time.Minute
	config.EnableTerminal = true
	config.EnableRBAC = true
	config.EnableWorkflow = true

	framework, err := NewE2EFramework(s.T(), config)
	s.Require().NoError(err)

	err = framework.Initialize()
	s.Require().NoError(err)

	s.framework = framework

	// Initialize terminal manager for session monitoring
	terminalConfig := terminal.DefaultConfig()
	terminalConfig.MaxSessions = 50 // Reasonable limit for monitoring
	terminalConfig.SessionTimeout = 2 * time.Minute

	terminalMgr, err := terminal.NewSessionManager(terminalConfig, framework.logger)
	s.Require().NoError(err)
	s.terminalManager = terminalMgr

	// Initialize HTTP client for API monitoring
	s.httpClient = &http.Client{
		Timeout: 10 * time.Second,
	}

	// Initialize monitoring data
	s.monitoringData = &SyntheticMonitoringData{
		TestResults:   make(map[string][]SyntheticTestResult),
		Alerts:        make([]SyntheticAlert, 0),
		SystemMetrics: SystemMetrics{ComponentStatus: make(map[string]string)},
		LastUpdate:    time.Now(),
	}
}

// TearDownSuite cleans up synthetic monitoring
func (s *SyntheticMonitoringSuite) TearDownSuite() {
	if s.terminalManager != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := s.terminalManager.(*terminal.DefaultSessionManager).Stop(ctx); err != nil {
			// Log error but continue cleanup - best effort cleanup
			_ = err
		}
	}

	if s.framework != nil {
		err := s.framework.Cleanup()
		s.Assert().NoError(err)

		// Export monitoring data for analysis
		s.exportMonitoringData()
	}
}

// TestContinuousHealthChecks performs ongoing health monitoring
func (s *SyntheticMonitoringSuite) TestContinuousHealthChecks() {
	err := s.framework.RunTest("continuous-health-checks", "synthetic-monitoring", func() error {
		s.framework.logger.Info("Starting continuous health checks")

		testDuration := 30 * time.Second
		if s.framework.config.OptimizeForCI {
			testDuration = 10 * time.Second
		}
		if testing.Short() {
			testDuration = 5 * time.Second
		}

		endTime := time.Now().Add(testDuration)
		checkInterval := 2 * time.Second

		healthCheckResults := make([]SyntheticTestResult, 0)

		for time.Now().Before(endTime) {
			startTime := time.Now()

			// Perform health checks on all components
			componentHealth := s.performComponentHealthChecks()
			responseTime := time.Since(startTime)

			// Determine overall health
			allHealthy := true
			for component, status := range componentHealth {
				if status != "healthy" {
					allHealthy = false
					s.generateAlert("warning",
						fmt.Sprintf("Component %s is %s", component, status),
						"continuous-health-checks")
				}
			}

			result := SyntheticTestResult{
				TestName:     "health-check",
				Timestamp:    startTime,
				Success:      allHealthy,
				ResponseTime: responseTime,
				Metrics: map[string]interface{}{
					"components_checked": len(componentHealth),
					"healthy_components": s.countHealthyComponents(componentHealth),
				},
			}

			if !allHealthy {
				result.ErrorMessage = "One or more components unhealthy"
			}

			healthCheckResults = append(healthCheckResults, result)
			s.recordTestResult("health-check", result)

			time.Sleep(checkInterval)
		}

		// Validate health check success rate
		successCount := 0
		for _, result := range healthCheckResults {
			if result.Success {
				successCount++
			}
		}

		successRate := float64(successCount) / float64(len(healthCheckResults)) * 100
		minSuccessRate := 90.0

		if successRate < minSuccessRate {
			return fmt.Errorf("health check success rate too low: %.2f%% < %.2f%%",
				successRate, minSuccessRate)
		}

		s.framework.logger.Info("Continuous health checks completed",
			"total_checks", len(healthCheckResults),
			"success_rate_percent", fmt.Sprintf("%.2f", successRate))

		return nil
	})

	s.Require().NoError(err)
}

// TestAPIEndpointMonitoring monitors critical API endpoints
func (s *SyntheticMonitoringSuite) TestAPIEndpointMonitoring() {
	err := s.framework.RunTest("api-endpoint-monitoring", "synthetic-monitoring", func() error {
		s.framework.logger.Info("Starting API endpoint monitoring")

		// Define critical endpoints to monitor
		endpoints := []struct {
			name       string
			path       string
			method     string
			maxLatency time.Duration
		}{
			{"controller-health", "/health", "GET", 500 * time.Millisecond},
			{"steward-list", "/api/v1/stewards", "GET", 1 * time.Second},
			{"system-status", "/api/v1/status", "GET", 200 * time.Millisecond},
		}

		testDuration := 20 * time.Second
		if s.framework.config.OptimizeForCI {
			testDuration = 5 * time.Second
		}
		if testing.Short() {
			testDuration = 3 * time.Second
		}

		var wg sync.WaitGroup
		endTime := time.Now().Add(testDuration)

		for _, endpoint := range endpoints {
			wg.Add(1)
			go func(ep struct {
				name       string
				path       string
				method     string
				maxLatency time.Duration
			}) {
				defer wg.Done()
				s.monitorEndpoint(ep.name, ep.path, ep.method, ep.maxLatency, endTime)
			}(endpoint)
		}

		wg.Wait()

		s.framework.logger.Info("API endpoint monitoring completed")
		return nil
	})

	s.Require().NoError(err)
}

// TestTerminalSessionMonitoring monitors terminal session health
func (s *SyntheticMonitoringSuite) TestTerminalSessionMonitoring() {
	// Story #294 Phase 4: Terminal monitoring with MQTT-connected stewards

	err := s.framework.RunTest("terminal-session-monitoring", "synthetic-monitoring", func() error {
		s.framework.logger.Info("Starting terminal session monitoring with MQTT stewards")

		// Register steward with controller for terminal testing (Phase 3 MQTT framework)
		tenantID := "synthetic-terminal-tenant"
		registered, err := s.framework.RegisterStewardWithController("synthetic-monitor-steward", tenantID)
		if err != nil {
			return fmt.Errorf("failed to register steward: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()

		// Steward is already connected via MQTT - verify connection
		if !registered.MQTTClient.IsConnected() {
			return fmt.Errorf("steward MQTT connection not established")
		}
		s.framework.logger.Info("MQTT steward connected for terminal monitoring",
			"steward_id", registered.StewardID)

		time.Sleep(500 * time.Millisecond) // Brief delay for MQTT connection stability

		testDuration := 15 * time.Second
		if s.framework.config.OptimizeForCI {
			testDuration = 5 * time.Second
		}
		if testing.Short() {
			testDuration = 3 * time.Second
		}

		sessionResults := make([]SyntheticTestResult, 0)
		endTime := time.Now().Add(testDuration)

		sessionCount := 0
		for time.Now().Before(endTime) {
			sessionCount++
			startTime := time.Now()

			// Create test session using MQTT-connected steward
			req := &terminal.SessionRequest{
				StewardID: registered.StewardID,
				UserID:    fmt.Sprintf("synthetic-user-%d", sessionCount),
				Shell:     "bash",
				Cols:      80,
				Rows:      24,
			}

			session, err := s.terminalManager.CreateSession(ctx, req)
			responseTime := time.Since(startTime)

			result := SyntheticTestResult{
				TestName:     "terminal-session-creation",
				Timestamp:    startTime,
				Success:      err == nil,
				ResponseTime: responseTime,
				Metrics: map[string]interface{}{
					"session_count": sessionCount,
				},
			}

			if err != nil {
				result.ErrorMessage = err.Error()
				s.generateAlert("warning",
					fmt.Sprintf("Terminal session creation failed: %v", err),
					"terminal-session-monitoring")
			} else {
				// Test session functionality
				if err := session.Start(ctx); err != nil {
					result.Success = false
					result.ErrorMessage = fmt.Sprintf("Session start failed: %v", err)
				} else {
					// Write test command
					if err := session.WriteData(ctx, []byte("echo 'synthetic test'\n")); err != nil {
						result.Success = false
						result.ErrorMessage = fmt.Sprintf("Session write failed: %v", err)
					}
				}

				// Clean up session
				if err := s.terminalManager.TerminateSession(ctx, session.ID); err != nil {
					// Log error but continue test
					_ = err
				}
			}

			sessionResults = append(sessionResults, result)
			s.recordTestResult("terminal-session-creation", result)

			time.Sleep(500 * time.Millisecond)
		}

		// Validate session creation success rate
		successCount := 0
		var totalLatency time.Duration
		for _, result := range sessionResults {
			if result.Success {
				successCount++
				totalLatency += result.ResponseTime
			}
		}

		successRate := float64(successCount) / float64(len(sessionResults)) * 100
		avgLatency := totalLatency / time.Duration(max(int64(successCount), 1))

		minSuccessRate := 95.0
		maxAvgLatency := 1 * time.Second

		if successRate < minSuccessRate {
			return fmt.Errorf("terminal session success rate too low: %.2f%% < %.2f%%",
				successRate, minSuccessRate)
		}

		if avgLatency > maxAvgLatency {
			return fmt.Errorf("terminal session average latency too high: %v > %v",
				avgLatency, maxAvgLatency)
		}

		s.framework.logger.Info("Terminal session monitoring completed",
			"sessions_tested", len(sessionResults),
			"success_rate_percent", fmt.Sprintf("%.2f", successRate),
			"avg_latency", avgLatency)

		return nil
	})

	s.Require().NoError(err)
}

// TestResourceUsageMonitoring monitors system resource consumption
func (s *SyntheticMonitoringSuite) TestResourceUsageMonitoring() {
	err := s.framework.RunTest("resource-usage-monitoring", "synthetic-monitoring", func() error {
		s.framework.logger.Info("Starting resource usage monitoring")

		testDuration := 20 * time.Second
		if s.framework.config.OptimizeForCI {
			testDuration = 5 * time.Second
		}
		if testing.Short() {
			testDuration = 3 * time.Second
		}

		endTime := time.Now().Add(testDuration)
		samples := make([]SystemMetrics, 0)

		for time.Now().Before(endTime) {
			metrics := s.collectSystemMetrics()
			samples = append(samples, metrics)

			// Check for resource usage alerts
			if metrics.AvailabilityPercent < 95.0 {
				s.generateAlert("critical",
					fmt.Sprintf("System availability dropped to %.2f%%", metrics.AvailabilityPercent),
					"resource-usage-monitoring")
			}

			if metrics.ErrorRate > 5.0 {
				s.generateAlert("warning",
					fmt.Sprintf("Error rate increased to %.2f%%", metrics.ErrorRate),
					"resource-usage-monitoring")
			}

			time.Sleep(2 * time.Second)
		}

		// Analyze resource usage trends
		if len(samples) > 0 {
			avgAvailability := s.calculateAverageAvailability(samples)
			avgErrorRate := s.calculateAverageErrorRate(samples)

			s.framework.logger.Info("Resource usage monitoring completed",
				"samples_collected", len(samples),
				"avg_availability_percent", fmt.Sprintf("%.2f", avgAvailability),
				"avg_error_rate_percent", fmt.Sprintf("%.2f", avgErrorRate))

			// Update system metrics
			s.updateSystemMetrics(samples[len(samples)-1])
		}

		return nil
	})

	s.Require().NoError(err)
}

// TestMQTTStewardHealthMonitoring monitors MQTT-connected steward health
// Story #294 Phase 4: Synthetic monitoring for MQTT+QUIC stewards
func (s *SyntheticMonitoringSuite) TestMQTTStewardHealthMonitoring() {
	err := s.framework.RunTest("mqtt-steward-health-monitoring", "synthetic-monitoring", func() error {
		s.framework.logger.Info("Starting MQTT steward health monitoring")

		// Register stewards with controller for monitoring
		stewardCount := 2
		if s.framework.config.OptimizeForCI {
			stewardCount = 1
		}
		if testing.Short() {
			stewardCount = 1
		}

		registeredStewards := make([]*RegisteredSteward, stewardCount)
		tenantID := "synthetic-monitoring-tenant"

		// Register stewards
		for i := 0; i < stewardCount; i++ {
			stewardName := fmt.Sprintf("synth-steward-%d", i)
			registered, err := s.framework.RegisterStewardWithController(stewardName, tenantID)
			if err != nil {
				return fmt.Errorf("failed to register steward %s: %w", stewardName, err)
			}
			registeredStewards[i] = registered
			s.framework.logger.Info("Registered steward for monitoring",
				"steward_id", registered.StewardID,
				"tenant_id", tenantID)
		}

		// Monitor health over time
		testDuration := 15 * time.Second
		if s.framework.config.OptimizeForCI {
			testDuration = 5 * time.Second
		}
		if testing.Short() {
			testDuration = 3 * time.Second
		}

		endTime := time.Now().Add(testDuration)
		checkInterval := 2 * time.Second
		healthCheckResults := make([]SyntheticTestResult, 0)

		for time.Now().Before(endTime) {
			startTime := time.Now()

			// Check MQTT connection health for all stewards
			healthyCount := 0
			disconnectedStewards := make([]string, 0)

			for _, registered := range registeredStewards {
				if registered.MQTTClient != nil && registered.MQTTClient.IsConnected() {
					healthyCount++
				} else {
					disconnectedStewards = append(disconnectedStewards, registered.StewardID)
				}
			}

			allHealthy := healthyCount == len(registeredStewards)
			responseTime := time.Since(startTime)

			result := SyntheticTestResult{
				TestName:     "mqtt-steward-health",
				Timestamp:    startTime,
				Success:      allHealthy,
				ResponseTime: responseTime,
				Metrics: map[string]interface{}{
					"total_stewards":        len(registeredStewards),
					"healthy_stewards":      healthyCount,
					"disconnected_stewards": len(disconnectedStewards),
				},
			}

			if !allHealthy {
				result.ErrorMessage = fmt.Sprintf("%d stewards disconnected: %v",
					len(disconnectedStewards), disconnectedStewards)
				s.generateAlert("warning",
					fmt.Sprintf("MQTT stewards disconnected: %v", disconnectedStewards),
					"mqtt-steward-health-monitoring")
			}

			healthCheckResults = append(healthCheckResults, result)
			s.recordTestResult("mqtt-steward-health", result)

			time.Sleep(checkInterval)
		}

		// Validate health check success rate
		successCount := 0
		for _, result := range healthCheckResults {
			if result.Success {
				successCount++
			}
		}

		successRate := float64(successCount) / float64(len(healthCheckResults)) * 100
		minSuccessRate := 90.0

		if successRate < minSuccessRate {
			return fmt.Errorf("MQTT steward health check success rate too low: %.2f%% < %.2f%%",
				successRate, minSuccessRate)
		}

		s.framework.logger.Info("MQTT steward health monitoring completed",
			"total_checks", len(healthCheckResults),
			"success_rate_percent", fmt.Sprintf("%.2f", successRate),
			"stewards_monitored", len(registeredStewards))

		return nil
	})

	s.Require().NoError(err)
}

// Helper methods for synthetic monitoring

func (s *SyntheticMonitoringSuite) performComponentHealthChecks() map[string]string {
	componentHealth := make(map[string]string)

	// Check controller health (includes MQTT broker)
	if s.framework.controller != nil {
		componentHealth["controller"] = "healthy"
		// MQTT broker is embedded in controller (Story #294 Phase 4)
		componentHealth["mqtt-broker"] = "healthy"
	} else {
		componentHealth["controller"] = "unhealthy"
		componentHealth["mqtt-broker"] = "unhealthy"
	}

	// Check registered stewards health via MQTT (Story #294 Phase 4)
	registeredCount := len(s.framework.registeredStewards)
	if registeredCount > 0 {
		// Count healthy MQTT connections
		healthyCount := 0
		for _, registered := range s.framework.registeredStewards {
			if registered.MQTTClient != nil && registered.MQTTClient.IsConnected() {
				healthyCount++
			}
		}
		if healthyCount == registeredCount {
			componentHealth["mqtt-stewards"] = "healthy"
		} else if healthyCount > 0 {
			componentHealth["mqtt-stewards"] = "degraded"
		} else {
			componentHealth["mqtt-stewards"] = "unhealthy"
		}
	}

	// Check certificate manager health
	if s.framework.certManager != nil {
		componentHealth["cert-manager"] = "healthy"
	} else {
		componentHealth["cert-manager"] = "unhealthy"
	}

	// Check RBAC manager health
	if s.framework.rbacManager != nil {
		componentHealth["rbac-manager"] = "healthy"
	} else {
		componentHealth["rbac-manager"] = "unhealthy"
	}

	// Check terminal manager health
	if s.terminalManager != nil {
		activeSessions := s.terminalManager.GetActiveSessions()
		if len(activeSessions) >= 0 { // Always true, but validates the call works
			componentHealth["terminal-manager"] = "healthy"
		}
	} else {
		componentHealth["terminal-manager"] = "unhealthy"
	}

	return componentHealth
}

func (s *SyntheticMonitoringSuite) countHealthyComponents(componentHealth map[string]string) int {
	count := 0
	for _, status := range componentHealth {
		if status == "healthy" {
			count++
		}
	}
	return count
}

func (s *SyntheticMonitoringSuite) monitorEndpoint(name, path, method string, maxLatency time.Duration, endTime time.Time) {
	for time.Now().Before(endTime) {
		startTime := time.Now()

		// In a real implementation, this would make HTTP requests to actual endpoints
		// For testing, simulate the request
		responseTime := time.Duration(50+len(path)*2) * time.Millisecond
		success := responseTime < maxLatency

		result := SyntheticTestResult{
			TestName:     name,
			Timestamp:    startTime,
			Success:      success,
			ResponseTime: responseTime,
			Metrics: map[string]interface{}{
				"endpoint": path,
				"method":   method,
			},
		}

		if !success {
			result.ErrorMessage = fmt.Sprintf("Response time %v exceeded max latency %v", responseTime, maxLatency)
			s.generateAlert("warning",
				fmt.Sprintf("Endpoint %s exceeded latency SLA: %v > %v", name, responseTime, maxLatency),
				"api-endpoint-monitoring")
		}

		s.recordTestResult(name, result)

		time.Sleep(2 * time.Second)
	}
}

func (s *SyntheticMonitoringSuite) collectSystemMetrics() SystemMetrics {
	// In a real implementation, this would collect actual system metrics
	// For testing, return simulated metrics
	return SystemMetrics{
		AvailabilityPercent: 99.5,
		AverageResponseTime: 150 * time.Millisecond,
		ErrorRate:           1.2,
		ActiveSessions:      len(s.terminalManager.GetActiveSessions()),
		TotalRequests:       1000,
		LastHealthCheck:     time.Now(),
		ComponentStatus: map[string]string{
			"controller":       "healthy",
			"cert-manager":     "healthy",
			"rbac-manager":     "healthy",
			"terminal-manager": "healthy",
		},
	}
}

func (s *SyntheticMonitoringSuite) generateAlert(severity, message, testName string) {
	alert := SyntheticAlert{
		AlertID:   fmt.Sprintf("alert-%d", time.Now().UnixNano()),
		Severity:  severity,
		Message:   message,
		TestName:  testName,
		Timestamp: time.Now(),
		Resolved:  false,
	}

	s.monitoringData.mu.Lock()
	s.monitoringData.Alerts = append(s.monitoringData.Alerts, alert)
	s.monitoringData.mu.Unlock()

	s.framework.logger.Warn("Synthetic monitoring alert generated",
		"alert_id", alert.AlertID,
		"severity", severity,
		"message", message,
		"test_name", testName)
}

func (s *SyntheticMonitoringSuite) recordTestResult(testName string, result SyntheticTestResult) {
	s.monitoringData.mu.Lock()
	if s.monitoringData.TestResults[testName] == nil {
		s.monitoringData.TestResults[testName] = make([]SyntheticTestResult, 0)
	}
	s.monitoringData.TestResults[testName] = append(s.monitoringData.TestResults[testName], result)
	s.monitoringData.LastUpdate = time.Now()
	s.monitoringData.mu.Unlock()
}

func (s *SyntheticMonitoringSuite) calculateAverageAvailability(samples []SystemMetrics) float64 {
	if len(samples) == 0 {
		return 0.0
	}

	total := 0.0
	for _, sample := range samples {
		total += sample.AvailabilityPercent
	}
	return total / float64(len(samples))
}

func (s *SyntheticMonitoringSuite) calculateAverageErrorRate(samples []SystemMetrics) float64 {
	if len(samples) == 0 {
		return 0.0
	}

	total := 0.0
	for _, sample := range samples {
		total += sample.ErrorRate
	}
	return total / float64(len(samples))
}

func (s *SyntheticMonitoringSuite) updateSystemMetrics(latest SystemMetrics) {
	s.monitoringData.mu.Lock()
	s.monitoringData.SystemMetrics = latest
	s.monitoringData.mu.Unlock()
}

func (s *SyntheticMonitoringSuite) exportMonitoringData() {
	s.monitoringData.mu.RLock()
	defer s.monitoringData.mu.RUnlock()

	// Export monitoring data as JSON for external analysis
	data, err := json.MarshalIndent(s.monitoringData, "", "  ")
	if err != nil {
		s.framework.logger.Error("Failed to marshal monitoring data", "error", err)
		return
	}

	s.framework.logger.Info("Synthetic monitoring data exported",
		"data_size_bytes", len(data),
		"test_results_count", len(s.monitoringData.TestResults),
		"alerts_count", len(s.monitoringData.Alerts))

	// In a real implementation, this would be sent to monitoring systems
	// For testing, just log that export occurred
}

// TestSyntheticMonitoring runs the synthetic monitoring test suite
func TestSyntheticMonitoring(t *testing.T) {
	// Only run synthetic monitoring tests if explicitly enabled
	if testing.Short() {
		t.Skip("Skipping synthetic monitoring tests in short mode")
	}

	suite.Run(t, &SyntheticMonitoringSuite{})
}
